### ISSUE TITLE
Enhance LookupFieldDefinition - support CountRelated in CSOM provision

### ISSUE THREAD

**Issue by sergeisnitko** [SubPointSolutions/spmeta2#1018]
**SPMeta2 CSOM Standard 1.2.120**

Hello, @SubPointSupport 

Is it possible to support the provision of CountRelated option of LookupFieldDefinition in CSOM. 
I found that it works only in SSOM and doesn't work in CSOM (#531). The field is interpreted like a standard lookup.
![image](https://cloud.githubusercontent.com/assets/7835251/25218095/49aa7a58-25b2-11e7-8e31-3499b5548d0f.png)

I understand that there is no property for CountRelated in CSOM, but it could be done with updating of the SchemaXml. Like this:
```c#
OpenedField.SchemaXml = OpenedField.SchemaXml.ReplaceXmlAttributeValue("CountRelated", "TRUE").ReplaceXmlAttributeValue("ReadOnly", "TRUE");

```

Thank you!

**Comment by SubPointSupport** [comment]
@sergeisnitko, okay, we'll see what can be done.

Right now you can leverage .AdditionalAttributes as following:
```cs
AdditionalAttributes.Add(new FieldAttributeValue { Name = "CountRelated", Value = "TRUE" });
```

Everything in .AdditionalAttributes is added to the field's XML during THE FIRST provision. Won't help with updates but at lest you've got an option to get the very first provision right.

We do some replacement for note field, can add something for lookup as well.
