### ISSUE TITLE
Incorrect provision order for navigation nodes

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#1019]
SPMeta2 seems to have incorrect provisioning order for navigation nodes. Raised by @digital88, more details can be found here:
https://github.com/SubPointSolutions/spmeta2/issues/1017#issuecomment-295664190

![image](https://cloud.githubusercontent.com/assets/10961828/25225422/00f6e086-25ca-11e7-8010-377624f70430.png)
I created child web, then added quick launch nav node for that web in parent web. SPMeta provisioned quick launch nav nodes first, which failed, because child web is not yet created.

**Comment by SubPointSupport** [comment]
@digital88, what are the navigation definitions? Can't catch it, the following model works well:

```cs
var subWebDef = ModelGeneratorService.GetRandomDefinition<WebDefinition>(def =>
            {

            });

            var quickNavigationDef = ModelGeneratorService.GetRandomDefinition<QuickLaunchNavigationNodeDefinition>(def =>
            {
                def.Url = string.Format("~sitecollection/{0}/SitePages/Home.aspx", subWebDef.Url);
            });

            var model = SPMeta2Model.NewWebModel(web =>
            {
                web.AddWeb(subWebDef);
                web.AddQuickLaunchNavigationNode(quickNavigationDef);
            });
```

**Comment by digital88** [comment]
Quick Launch Nav Node:
![image](https://cloud.githubusercontent.com/assets/10961828/25228222/49080c38-25d4-11e7-94fc-f76bd818aecd.png)

Child web:
![image](https://cloud.githubusercontent.com/assets/10961828/25228278/7d243500-25d4-11e7-8e3c-dec6bcbde6e4.png)

**Comment by SubPointSupport** [comment]
Still works well for both CSOM/SSOM, you sure q1-q7 nodes in the model belong to the subweb?

Closing until definitions and the model which can clearly replicate the issue are provided. For the further tickets, we not going to accept screens. Create a new issue and follow the template.

**Comment by digital88** [comment]
Sorry, I can't copy paste from my work machine. It will take me some time to retype all definitions.

**Comment by SubPointSupport** [comment]
Not gonna guess either. Take your time, only two definitions and the model are needed. It can also be suggested to test your model locally as it might not be an issue after all.

**Comment by digital88** [comment]
My environment: Sharepoint 2016 ENG + RUS lang pack, August 2016 CU. SPMeta2 v1.2.110 CSOM.
New fresh site collection at /sites/test (site LCID = 1049 (Russian), template STS#0).

This model fails:
```cs
var model = SPMeta2Model.NewWebModel(web =>
{
  web.AddWeb(new WebDefinition()
    {
      Title = "Forum",
      LCID = 1049,
      Url = "Forum",
      WebTemplate = BuiltinWebTempaltes.Collaboration.CommunitySite
    });
  web.AddQuickLaunchNavigationNode(new QuickLaunchNavigationNodeDefinition()
    {
      Title = "Forum",
      Url = "~sitecollection/Forum"
    });
});
svc.DeployWebModel(ctx, model);
```

This one works fine:
```cs
var model = SPMeta2Model.NewWebModel(web =>
{
  web.AddWeb(new WebDefinition()
    {
      Title = "Forum",
      LCID = 1049,
      Url = "Forum",
      WebTemplate = BuiltinWebTempaltes.Collaboration.CommunitySite
    });
});
var model2 = SPMeta2Model.NewWebModel(web =>
{
  web.AddQuickLaunchNavigationNode(new QuickLaunchNavigationNodeDefinition()
    {
      Title = "Forum",
      Url = "~sitecollection/Forum"
    });
});
svc.DeployWebModel(ctx, model);
svc.DeployWebModel(ctx, model2);
```

Here is stack trace:
![image](https://cloud.githubusercontent.com/assets/10961828/25240200/e9a5b67e-25fa-11e7-9641-0948705dd008.png)

**Comment by SubPointSupport** [comment]
Confirming the issue! Thank you for your patience, sorting out.

**Comment by SubPointSupport** [comment]
Sweet, fixed.
