### ISSUE TITLE
Enhance ListDefinition - add EnableAssignToEmail property

### ISSUE THREAD

**Issue by andreasblueher** [SubPointSolutions/spmeta2#1023]
With SharePoint 2013 EnableAssignToEmail is not available via UI anymore. The only way so enable automatic mail is to use PowerShell like [this](https://christopherclementen.wordpress.com/2014/07/28/sharepoint-2013-task-list-does-not-send-mail-on-task-assignation-2/).

I tried set this property via SPMeta2 PropertyBag, but it didn't work. Does Propertybag not work for boolean values?

`PropertyBag = new List<PropertyBagValue>
                {
                    new PropertyBagValue("EnableAssignToEmail", true.ToString())
                } `

**Comment by SubPointSupport** [comment]
Done, available only for SSOM.Done, available only for SSOM.

**Comment by andreasblueher** [comment]
Thanks for the fast reaction and implementation. One thought which crossed my mind: What happens if you try to set this value if it's a document library? Does SharePoint complain or does it ignore the value?

**Comment by SubPointSupport** [comment]
No worries, we were working on other stuff and this one was too easy to implement.

Absolutely no idea on doc libs :)
