### ISSUE TITLE
Best practices for large models

### ISSUE THREAD

**Issue by andreasblueher** [SubPointSolutions/spmeta2#1028]
Hello guys,

through using SPMeta more and more we're developing more complex and larger models with every time we used it. Having the concept of incremental updates is a huge help for us regarding ongoing deployment aka updates, but for the initial deployment we keep running into timeout (iis wise).

We started to split SPMeta deployment into multiple features, but in the end it's adding complexity we would like to avoid. After all the real time logging would be way cooler if it could be deployed in one feature.

Increasing IIS timeout could be an option, but I would rather not do it and you guys most of the time have great ideas and a lot of experience ;-). Kind regards, Andreas

**Comment by avishnyakov** [comment]
Hey @andreasblueher, could you please provide more context?

It seems that you are talking about SSOM based deployment and, in particular, feature activation under *.wsp packages? Is that right or you have a console app or even CSOM deployment? Also, what do you mean by large models? Is it all about time required for provisioning, amount of artifacts, amount of models?

If SSOM  guess is the right one and feature activation is used (or some other server side logic), then we always hit default SharePoint http request which is 90-120 seconds. That comes with the default config for a particular web application under its web.config, such as following:
```
C:\inetpub\wwwroot\wss\VirtualDirectories\80\web.config
```

That is out of the box SharePoint behavior, nothing much we can do here apart changing the default value. 

Fundamentally, the only two strategies here are these:
1) Continue running provisioning code under SharePoint context 
2) Move outside of SharePoint

The first one comes with default SharePoint limitation and we aren't gonna discuss it. Not us, sorry, all about out of the box SharePoint behavior.

The second one goes with multiple options. Could be CSOM/SSOM provision, PowerShell based script, provider hosted app and so on. Depending on a particular scenario, it might be considered having heavy SSOM based features under *.wsp (such as time jobs or something else) and then the rest under CSOM based provision - console based "installator", MSI - desktop app (we are building metapack for this sole purpose), provider hosted app with nice UI (similar to PnP Parther Pack or something like that) to get the rest of the things up and running.

Hope that help to get find the best solution here.

**Comment by SubPointSupport** [comment]
@andreasblueher is there anything else here we can help?

**Comment by andreasblueher** [comment]
Sorry for missing some key information. Yes it's a SSOM, *.wsp, feature based solution with models being deployed aswell as TimerJobs, EventReceiver code and other SharePoint artifacts.

I think you're pointing me into the right direction and that would be to not deploy everything from feature eventreceiver. I liked the idea of having everything in one place so after activating every available feature you would have the solution running. Since we're usually deploying a wide range of artifacts including TimerJobs, Webparts, Apps, Fields, Lists, ..... and given the fact we started with SSOM years ago, this still feels like the way to go.

Metapack sounds promising and I'll try to look into it soon. For now I'll leave the solution with multiple features as is, but looking forward I'll try out metapack and consider other deployment options. 

Thank you very much

**Comment by SubPointSupport** [comment]
Too easy!

**Comment by andreasblueher** [comment]
Right ;-)?

Sometimes you're stuck with an problem and trying to figure it out, while the solution would be do not have this issue in the first place. :)

**Comment by SubPointSupport** [comment]
Indeed, it is. Hope that helps, let us know if there is anything else we can help you with.
