### ISSUE TITLE
List UserCustomAction not created, CSOM v1.2.120

### ISSUE THREAD

**Issue by esuhendra** [SubPointSolutions/spmeta2#1031]
Hi guys,

Just updated SPMeta2 package to v1.2.120 CSOM and for some reason, the user custom actions for lists are not being created. If I revert back to v1.2.110, the user custom actions are created.

Here's my UserCustomAction definition:
```
model.AddHostList(listDef, list =>
{
    list.AddUserCustomAction(new UserCustomActionDefinition() {
        RegistrationType = "List",
        CommandUIExtension = "<CommandUIExtension>
        <CommandUIDefinitions>
          <CommandUIDefinition Location="Ribbon.ListItem.Actions.Controls._children">
            <Button Id="{EC3501CD-CF6B-44FD-A87F-77C76544E313}" Command="{0E779640-B723-403B-B687-FEC416BE3240}" Image32by32="/_catalogs/masterpage/img/email.png" Image16by16="/_catalogs/masterpage/img/email.png" Sequence="3" LabelText="Email Bulletin" Description="" TemplateAlias="o1" />
          </CommandUIDefinition>
        </CommandUIDefinitions>
        <CommandUIHandlers>
          <CommandUIHandler Command="{0E779640-B723-403B-B687-FEC416BE3240}" CommandAction="~site/_layouts/15/wfstart.aspx?List={ListId}&amp;ID={SelectedItemId}&amp;TemplateID=EEB11ABB-D1B9-4A66-8F82-1E0899FDE2FF&amp;SubscriptionID=9FDB8AAA-EDE2-4D6D-9AA1-1CF530E614DD" EnabledScript="javascript:SP.ListOperation.Selection.getSelectedItems().length==1" />
        </CommandUIHandlers>
      </CommandUIExtension>",
        Name = "Email Bulletin List Ribbon",
        Location = "CommandUI.Ribbon.ListView",
    });
});
```
Has anything been changed with how to provision UserCustomAction for v1.2.120, or am I constructing the definition incorrectly?

**Comment by SubPointSupport** [comment]
This is unexpected, we do have a test to provision user custom action on a list level (as well as web and site levels) for both CSOM/SSOM. Let us have a deeper look, will get back on this one.

**Comment by esuhendra** [comment]
Thanks. Always appreciate your fast response.

**Comment by SubPointSupport** [comment]
In progress.

**Comment by SubPointSupport** [comment]
Tested your model, UserCustomActionDefinition is deployed as expected. Most likely, something wrong with RegistrationType/CommandUIExtension/Location properties. Also, the initial source code has not been changed for quite a time. Closing for the time being unless a further work is required.

**Comment by esuhendra** [comment]
No worries. I'll see what went wrong with my code. Thanks for looking into this.
