### ISSUE TITLE
TaskStatus vs Status field

### ISSUE THREAD

**Issue by andreasblueher** [SubPointSolutions/spmeta2#1039]
Hello,

I'm using SSOM SP 2013 1.2.120 on Premise.

BuiltInInternalFieldNames contains an element "TaskStatus" with field id {c15b34c3-ce7d-490a-b133-3f4de8801b76}. After creating a new task list my status field has the same guid but the internal name is "Status" so using BuiltInInternalFieldNames.TaskStatus does only work for some other type of tasklist I suppose.

The list I've created has TemplateType = BuiltInListTemplateTypeId.Tasks

How is it possible to have the same id with different internal names for default SharePoint fields?

**Comment by vladivanovrf** [comment]
It should be a question to Microsoft...

**Comment by andreasblueher** [comment]
In this case the BuiltInInternalFieldNames is not complete, am I right? Shouldn't be there another BuiltInFieldDefinition plus BuiltInInternalFieldNames.Status?

**Comment by SubPointSupport** [comment]
Hey @andreasblueher, sorry for the late response. Frankly saying, not sure what's going on here. 

There are a lot of fields in SharePoint, we aren't really tracking or knowing which one should be in a list or not.

Now, in SharePoint 2013 there are two tasks list - a classic one, and the modern task list with the timeline. Maybe that's the root of the issue you see? 

Finally, how does the model look like, what's the expected behaviour and what's wrong? So that we could replicate and have a deeper look into this issue?

**Comment by andreasblueher** [comment]
The model is too easy to attach. It's on list on a web with TemplateType = BuiltInListTemplateTypeId.Tasks.

I've than added an event receiver to this list to react on changes within this list and to avoid MagicStrings, I'm using both BuiltInInternalFieldNames plus my SPMeta FieldDefinitions.InternalName to access specific columns. 

For my task list I can use

BuiltInInternalFieldNames.Title
BuiltInInternalFieldNames.AssignedTo
BuiltInInternalFieldNames.Body
BuiltInInternalFieldNames.StartDate
BuiltInInternalFieldNames.DueDate
BuiltInInternalFieldNames.Priority
BuiltInInternalFieldNames.Predecessors

you name it. Every single column from default task contentType is available from the collection you provided. However, there is no equivalent for the "Status" column. The status column I'm having in my list has the same guid as the field TaskStatus in BuiltInInternalFieldNames.

// Summary:
//     Corresponds to built-in field with Title [Task Status], ID [c15b34c3-ce7d-490a-b133-3f4de8801b76]
//     and Group: [Core Task and Issue Columns]'
public static string TaskStatus;

But my internal name is not "TaskStatus" and it's rather "Status". So I was looking for an option to not using magicstring "Status" in my code.

**Comment by vladivanovrf** [comment]
It's Microsoft bug or "feature". I work with this field only by Id. Because it has different internal name in web content type and in list content type but id always the same.

**Comment by SubPointSupport** [comment]
That could be both SharePoint and kinda "us".

For the thing is that both BuiltInInternalFieldNames / BuiltInInternalFieldIds were generated from the SharePoint web site. We got all the fields, and then generated the code to reflect InternalNames / Ids from the site collection level fields.

If something dodgy is going on at the list level, well.. guys.. what do you want us to do? :)
Mean, we already pre-generated InternalNames/ID from the site level fields into BuiltInInternalFieldNames / BuiltInInternalFieldIds. What else we can do?

**Comment by andreasblueher** [comment]
@vladivanovrf Now I understand what you meant with your first answer. You're right, internal name for this column are different on web and list, but id is the same. My problem is that inside event receivers "AfterProperties" collection you can't use id. One could get the field by id and access AfterProperties hash with internalName afterwards, but that seems too complicated for the benefit I would get.

@SubPointSupport As I understand it now my best shot is to simply use the MagicString "Status" and don't worry about it. Adding a new BuiltInInternalFieldName with "Status" and the same Id doesn't appear to be a clean solution either.

Nothing here which could be improved, so I'll close the issue.

**Comment by SubPointSupport** [comment]
Sweet, thanks!
