### ISSUE TITLE
Missing WebpartDefinition for Search Core Result Webpart

### ISSUE THREAD

**Issue by andreasblueher** [SubPointSolutions/spmeta2#1041]
Based on [this yammer discussion](https://www.yammer.com/spmeta2feedback/#/Threads/show?threadId=902195092) I want to create this issue regarding a possible new definition.

We're using this webpart for SP2010, SP2013 and SP2016 whenever no enterprise features are available (which is the case most of the time for us).

**Comment by SubPointSupport** [comment]
Noted, thank you. We'll have a closer look and implement a new definition for this matter.

**Comment by SubPointSupport** [comment]
This one is in the progress. Aiming close this week.

@andreasblueher, what would be the common scenarios on this web part usage? What are the top properties you need, and cases to cover in regression tests?

**Comment by andreasblueher** [comment]
hey @SubPointSupport, today I didn't get a hold of a colleague of mine which I need to answer your question. I'll meet him tomorrow and get back to you as soon as possible.

**Comment by SubPointSupport** [comment]
Okay, works for us. We'll get a few other thing done, meanwhile. We'll be running full regression over the weekend so most likely we would have to push this one to the following week.

**Comment by andreasblueher** [comment]
Well .. I'm not sure on where to start. My first yammer post was vague and after reviewing the request it was wrong aswell. It appears that I was referencing the wrong webpart definition from msdn. After exporting one of the webparts I realized the webpart I am looking for is the [ResultScriptWebpart](https://msdn.microsoft.com/en-us/library/microsoft.office.server.search.webcontrols.resultscriptwebpart.aspx). 

The second file visualizes which properties use with this webpart and therefor would like to set them programmatically. I really would like to support you here, because that's a lot of properties. So please let me know if I can create the definition file.

How would you implement the DataProviderJSON?

[webpartexport.txt](https://github.com/SubPointSolutions/spmeta2/files/1108898/webpartexport.txt)
[Important Properties Search Webpart.zip](https://github.com/SubPointSolutions/spmeta2/files/1108945/Important.Properties.Search.Webpart.zip)

**Comment by SubPointSupport** [comment]
We already have ResultScriptWebPartDefinition. Works well for limited scenarios, here are the props exposed:

https://github.com/SubPointSolutions/spmeta2/blob/beta/SPMeta2/SPMeta2.Standard/Definitions/Webparts/ResultScriptWebPartDefinition.cs

DataProviderJSON needs to be constructed mannually, exported from existing web part or you can use dynamic + JSON serialization to render C# object into JSON.

Let us know how it work for you, we'll see what are the outstanding props to add into ResultScriptWebPartDefinition

**Comment by andreasblueher** [comment]
Oh gosh ... I searched for it, but I couldn't findt it because I was using SPMeta Foundation bib only :/. I'm so sorry.

I would like to provide some changes (PR) so it can be integrated into SPMeta. Do you like the idea or do you think this is an edge case for which there is no need? Where would you put the class for DataProviderJSON in your solution?

I'm adding some links which I found during my research which could help implementing this.

[https://carepoint.blogspot.de/2013/04/setting-dataprovider-for.html](Setting DataProvider no1)
[https://dinushaonline.blogspot.de/2014/02/add-search-query-text-programmatically.html](Setting DataProvider no2)
[https://reshmeeauckloo.wordpress.com/2016/10/15/update-search-result-web-part-query-text-and-result-source/](All properties from exported webpart)

**Comment by andreasblueher** [comment]
I tried to find time to improve this definition myself, but my current project situation doesn't seem to allow me to do this. I've found a colleague who's looking into this. For the time being, you can close this issue if you don't plan to change things on your side. We'll reference it once we come up with an improvement.

**Comment by SubPointSupport** [comment]
Having a PR from you. Is that the one?

**Comment by andreasblueher** [comment]
Yes, that's #1057 I was talking about. Closing this issue.

**Comment by SubPointSupport** [comment]
Cool, thanks!
