### ISSUE TITLE
StandardCSOMProvisionService vs StandardSSOMProvisionService

### ISSUE THREAD

**Issue by andreasblueher** [SubPointSolutions/spmeta2#1062]
Hey,

I was wondering why SSOMProvisionService allows you to provision and deploy ResultScriptWebpart aka SPMeta.SSOM.Standard component, while CSOMProvisionService throws an exception? The reason for that was the fact that CSOMProvisionService didn't have access to ResultScriptWebpartDefinitionHandler while SSOMProvisionService had no such issues.

Developing mostly SSOM features these days it took me some time to find the reason and it made me wonder while they're not behaving the same way.

p.s. Sorry for opening so many issues and being so active out of nothing

**Comment by SubPointSupport** [comment]
We need to look into this. Might be a initial bug in placing ResultScriptWebpart under wrong namespace or even library. 

Unfortunately, we might be required to run with it due to serialization and backward compatibilities issues. Again, let us have a closer look and figure out the story on this.

**Comment by SubPointSupport** [comment]
> p.s. Sorry for opening so many issues and being so active out of nothing

There is no such thing as "too much feedback" from the customer care perspective :)
Keep up a good work you do, @andreasblueher

**Comment by SubPointSupport** [comment]
Alright, so both handlers for ResultScriptWebpartDefinition for CSOM/SSOM are located under "SPMeta2.XXX.Standard" namespace and assemblies. Implemented as expected.

Not sure about the reason to have an impression for this one:
>I was wondering why SSOMProvisionService allows you to provision and deploy ResultScriptWebpart aka SPMeta.SSOM.Standard component, while CSOMProvisionService throws an exception? The reason for that was the fact that CSOMProvisionService didn't have access to ResultScriptWebpartDefinitionHandler while SSOMProvisionService had no such issues.

Would you please provide more context and how to replicate this issue, @andreasblueher? 
For the time being, closing this one. We'll reopen is there is a real issue here.
