### ISSUE TITLE
MetadataNavigationSettings Hierarchy missing Folders field

### ISSUE THREAD

**Issue by esuhendra** [SubPointSolutions/spmeta2#1064]
Hi guys,

This might be a bug or might be on purpose.

Using SPMeta2 package  v1.2.110 CSOM, I'm trying to set MetadataNavigationSettings KeyFilters without setting any Hierarchies. The key filters are set as it should be, but the Folders field is not set in Hierarchy fields. This causes the Column Default Values setting to not work properly (unable to select a folder to set default values).
I think this is because the HideFoldersNode attribute is only set when a Hierarchy is set in the MetadataNavigationSettingsConfig.cs.

If I set key filters from the SharePoint UI, the Folders is automatically added to the Hierarchy list.

```
        public void AddConfiguredHierarchy(MetadataNavigationHierarchyConfig item)
        {
            var currentKey = FindConfiguredKeyFilter(item.FieldId);

            if (currentKey == null)
            {
                var root = SettingDocument.Root;

                var parentNode = root.Descendants("NavigationHierarchies").FirstOrDefault();

                if (parentNode == null)
                {
                    parentNode = new XElement("NavigationHierarchies");
                    root.Add(parentNode);

                    var folderHierarchyNode = new XElement("FolderHierarchy");

                    folderHierarchyNode.SetAttribute("HideFoldersNode", "False");
                    parentNode.Add(folderHierarchyNode);
                }

                var newNode = new XElement("MetadataField");

                newNode.SetAttributeValue("FieldID", item.FieldId.ToString("D"));
                newNode.SetAttributeValue("FieldType", item.FieldType);

                newNode.SetAttributeValue("CachedName", item.CachedName);
                newNode.SetAttributeValue("CachedDisplayName", item.CachedDisplayName);

                parentNode.Add(newNode);
            }
        }
```
Should the HideFoldersNode be set regardless whether the hierarchy field is set or not?

**Comment by SubPointSupport** [comment]
Most likely bug. Really appreciate you raising this up.

**Comment by SubPointSupport** [comment]
Could you please share the model you use and more context on the "Folders" field?
How do you later see that "Column Default Values" does not work properly?

**Comment by esuhendra** [comment]
Sure.
Here's the model, 
~~~
model.AddList(defn, list =>
                    {
                        // Provision Key Filter
                        var keyFilter = new MetadataNavigationKeyFilter
                        {
                            FieldId = new Guid('{A48A75BD-A10F-47B6-9989-F36BA593BE67}')
                        };
                        var nav = new MetadataNavigationSettingsDefinition();
                        nav.KeyFilters.Add(keyFilter);
                        list.AddMetadataNavigationSettings(nav);
                });
~~~
I have a couple of folders in a library.

![image](https://user-images.githubusercontent.com/20235625/29697331-06e0f1a6-8981-11e7-9147-8bba2bdec437.png)

The managed metadata settings is as below

![image](https://user-images.githubusercontent.com/20235625/29697365-449d8630-8981-11e7-8cbe-b858399d75cd.png)

And going to the option 'Column Default Value Settings' and clicking a node on the tree hierarchy collapses the tree and setting default values only applied to the root folder.

![image](https://user-images.githubusercontent.com/20235625/29697544-5afa0056-8982-11e7-87a0-8e26557f921c.png)

**Comment by SubPointSupport** [comment]
Oh, sweet. Does not look good, let us fix this one and see what can be done.

**Comment by SubPointSupport** [comment]
@esuhendra, correct. It has to do with the default setting for NavigationHierarchies->FolderHierarchy-> HideFoldersNode=False setting. SSOM sets it by default, by the looks of things, but with CSOM we had to implement XML generation manually and seems to miss it.

Tested, replicated your issues. Fixed CSOM adding this XML attribute, all started working well.

**Comment by SubPointSupport** [comment]
Again, thanks for the hint with HideFoldersNode values. Great work!

**Comment by esuhendra** [comment]
Awesome! Thanks guys!

**Comment by SubPointSupport** [comment]
We need additional work done, then testing over the weekend and a new beta version Monday.
