### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by andreasblueher** [SubPointSolutions/spmeta2#1080]
Hey guys,

do you have plans when the next release is going to be out? Looking forward to the PRs I submitted and would like to use an official build instead of my custom build one.

Coming back to you for my other issues asap

**Comment by SubPointSupport** [comment]
Noted. Apart need to run off the official release, anything else holding you back?

**Comment by andreasblueher** [comment]
Nothing specific, but before I deploy a custom build to my customer and something fails afterwards I rather use official releases.

**Comment by SubPointSupport** [comment]
Noted, thanks.

**Comment by digital88** [comment]
So any plans to push next release this month? Or at least before end of this year? :)

**Comment by andreasblueher** [comment]
I don't want to push anything, but I would rather go back to updates without major fixes/changes and get them more often instead.

**Comment by SubPointSupport** [comment]
If we had a beta weekly with a major version monthly, would it solve your concerns, guys?

**Comment by andreasblueher** [comment]
I don't think weekly betas are necessary, but monthly or for that meaning
major releases on a regular basis would solve my request.

If you release a major version on the first Monday of the month (or
something similar) and a new piece of code is not ready, simply release it
next month.

Regarding the beta releases, those could be used to let people test more
complicated things before they go public.

Am 02.10.2017 10:25 nachm. schrieb "SubPointSupport" <
notifications@github.com>:

If we had a beta weekly with a major version monthly, would it solve your
concerns, guys?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SubPointSolutions/spmeta2/issues/1080#issuecomment-333654358>,
or mute the thread

**Comment by SubPointSupport** [comment]
Noted, thanks.

Obviously, we do have a hiccup with releases overt the last months. The old way of doing things wasn't scalable hence we focused on regression environment automation (packer/vagrant), regression testing strategy changes to cut time required for testing and sites/docs rewrite. Mostly internal stuff some of which is going to be public once polished.

Lack of automation and consistent setup across SP2013/2016 (including migration to VS15/17) also prevents other people of making commits and changes. These puzzles come as a single package on solving which we already spent June/September.

**Comment by avishnyakov** [comment]
SPMeta2 1.2.140, February 2018
> https://github.com/SubPointSolutions/spmeta2/releases/tag/1.2.140

NuGet 
> https://www.nuget.org/profiles/SubPointSupport

Btw, hitting almost 30000 downloads for SPMeta2.Core and 175000 altogether with other packages. 5 years soon!

**Comment by digital88** [comment]
Please, you cant just disapper for 6 month without a word. Notify your users about what is going on.

**Comment by SubPointSupport** [comment]
> Please, you cant just disapper for 6 month without a word. Notify your users about what is going on.

Noted, thanks!
