### ISSUE TITLE
Let AllowedInlineDownloadedMimeTypes be defined by SPMeta

### ISSUE THREAD

**Issue by andreasblueher** [SubPointSolutions/spmeta2#1087]
Hey guys,

some other edge case feature request from my side. For each webapplication one can define which MimeTypes will be handled stricly and which permissive. This is of course only available for SSOM.

* http://www.roberthiskey.com/2012/05/setting-permissive-handling-for.html
* http://jasonwarren.ca/add-and-remove-mime-types-from-sharepoint-powershell/
Cached version of the last link:
> https://web.archive.org/web/20171117030325/http://jasonwarren.ca:80/add-and-remove-mime-types-from-sharepoint-powershell/

**Comment by avishnyakov** [comment]
Sounds not too bad, thanks for raising this up, @andreasblueher 

It might be added to the WebApplicationDefinition by the looks of things. On the other hand, SharePoint DSC might be one of the options to get this configured as well.

When do you need this feature?

**Comment by andreasblueher** [comment]
How do you plan to integrate SharePoint DSC into SPMeta? Besides WebApplicationDefinition sounds like the best idea. 

Too bad the 2nd link I've put into this issue is not available anymore. I think I'll try to implement this myself :)

**Comment by avishnyakov** [comment]
Updated with a cached page for the last link. Google Cache is a dangerous thing.
> https://web.archive.org/web/20170607204648/http://jasonwarren.ca/add-and-remove-mime-types-from-sharepoint-powershell/

Raw script is here:
> https://raw.githubusercontent.com/chrisdee/Scripts/master/PowerShell/Working/SharePoint/SharePoint2013/SP2013AddAllowedInlineDownloadedMimeTypes.ps1

And original script with other goodies:
> https://github.com/chrisdee/Scripts/blob/master/PowerShell/Working/SharePoint/SharePoint2013/SP2013AddAllowedInlineDownloadedMimeTypes.ps1

As for integrations with DSC, not sure what to say here. SharePoint DSC does a great job for app configuration and deployoment, where SPMeta2 takes it where DSC stops, moving forward with the metadata privision. These two words are hardly connected, at least it woudn't be a good move to expand SPMeta2 into app configration space. 

At the end, why not to use DSC for app specific settings, and then run SPMeta2 for metadata? 
WebApplicationDefinition does sound like a good idea, that be the right place to look into.

**Comment by andreasblueher** [comment]
Thank you for looking into it. I have another question:

Why decided you to set DraftVersionVisibility for ListDefinition as a string while AddFieldOptions for FieldDefinition is an enum? I'm currently adding BrowserFileHandling to WebApplicationDefinition and ListDefinition and I'm not sure which way to choose. Enum seems to be the more failproove option

**Comment by avishnyakov** [comment]
It's all legacy, misdesign on our side which we could not have seen early.

AddFieldOptions was added a long time ago as a custom enum. That's how it should have been done. Every time you see strings or array of string instead of enum - that's pure legacy and wrong choice on our side. As a consequence, there is an impact on intellisense and inability to set enum value via string or array using binary operations, such as "&" and "|".

As an example, AddFieldOptions should actually be an enum. 

All this wasn't realised at the right time. Then, the idea was to carry on to have consistency and then refactor at some point, reworking all these problematic props into enums. That's how the idea of 1.3.0 was floating around for a while. As usage of SPMeta2 increased, complexity and tech dept has lead to the current state. Not that "it works don't change" is our motto but rather we weren't able to keep up with regression testing and load acrorss the board to hit 1.3.0 refactoring.

Ideally, this should be re-written into enums. It would produce havok and some migration cost, but everyone should see that this move is just unavoidable. 

What's your view on this issue?

**Comment by andreasblueher** [comment]
First of all I'll add BrowserFileHandling as an enum.

To your other question: Having legacy decision and backwardscompatibility is one thing, but ultimately this can't be the argument to keep things like they used to be forever. SharePoint and .NET have been evolving a lot and my mantra when it comes to programming is to leave a method or class in a better state than it was when I started working on it.

I've seen many tools explicitely stating "breaking changes" in every release. While I don't think SPMeta should have those breaking changes in every release, I think people would understand if they appear from time to time. 

We had a similar discussion regarding the supported .NET version and I'm also a fan of evolving and starting to support newer version escpecially with SP2016 being the only supported SharePoint version very soon. SP2013 SP1 mainstream support ends in April. I would rather have a legacy version of SPMeta for older SP versions (my personal opinion).

**Comment by avishnyakov** [comment]
Absolutely agree with everything said. No, legacy/backward compatibility can't be an excuse to stay yeard below. We did that, and got you rather concerned very recently :) 

Right you are, we are already running SPMeta2 regression on shiny Win2016 + SP2016 Feature Pack 2 + VS2015. Must admit, it feels good. Running on the metabox platform so kudos to @shurick81 for that. Tracking it here, there are a few challenges we are solving this week before pushing 1.2.140
> Migrate regression testing Win2016, SP2016 and VS2015 platform #1096

As for SP2013 SP1 end of life, that's where it's so tempting to drop the ball and support only SP2016 with re-engineered 1.3.xx. Supporting 2010/2013 and 2016 across the board coping with the new features available is really, really hard; it's a complex engineering challenge giving a nature of SharePoint and CSOM/SSOM which we support. Feb looks like some of the tech dept and then we are free to do more amazing things.

**Comment by andreasblueher** [comment]
Back to the topic of AllowedInlineDownloadedMimeTypes. I started with implementing BrowserFileHandling property for List and Webapplication and than tried to implement the MimeTypes logik.

The base question is: Should one be able to remove default mime types or only to add new supported mime types?

Do you agree or disagree that the new WebApplication property should be named "AdditionalInlineDownloadedMimeTypes" rather than implementing a list containing all default "AllowedInlineDownloadedMimeTypes" for which new mimetypes could be added or existing ones could be removed. Because the code would be different if you could only add new mime types rather than being able to add or delete mime types.

**Comment by avishnyakov** [comment]
> The base question is: Should one be able to remove default mime types or only to add new supported mime types?

I'd go with additional "ClearXXX" bool? property. Similar to what we have with breaking role permission to clear up scopes. If set, reset default mime types, and add ours. If not - add on top.

Good enough?

**Comment by SubPointSupport** [comment]
Implemented in dev branch.

Added new props into WebApplicationDefinition:
* AllowedInlineDownloadedMimeTypes
* ShouldOverrideAllowedInlineDownloadedMimeTypes

https://github.com/SubPointSolutions/spmeta2/blob/dev/SPMeta2/SPMeta2/Definitions/WebApplicationDefinition.cs#L145


By default, new types are added on top. ShouldOverrideAllowedInlineDownloadedMimeTypes property can be used to reset this collection as per definition spec.

Implemented SSOM validator, added a few more tests to cover this scenario:
* CanDeploy_Existing_WebApplication
* CanDeploy_Existing_WebApplication_With_AllowedInlineDownloadedMimeTypes
* CanDeploy_Existing_WebApplication_With_AllowedInlineDownloadedMimeTypes_Reset

Example of CanDeploy_Existing_WebApplication_With_AllowedInlineDownloadedMimeTypes_Reset test and usage:

https://github.com/SubPointSolutions/spmeta2/blob/dev/SPMeta2/SPMeta2.Regression.Tests/Impl/Scenarios/WebApplicationScenariosTests.cs#L100
