### ISSUE TITLE
Allow to set SPWeb.SiteLogoUrl or Web.SiteLogoUrl

### ISSUE THREAD

**Issue by andreasblueher** [SubPointSolutions/spmeta2#1092]
Hello,

currently it's not possible to set SiteLogoUrl using SPMeta. Not sure if this should be a new definition or if it could be integrated to another definition, but it exists for CSOM and SSOM. Maybe it has been added to CSOM at a later stage, but with up2date csom dll it's available.

**Comment by andreasblueher** [comment]
There appears to be an option to set SiteLogoUrl for WebDefinition and I'm not sure why I couldn't find them last time. Issue closed because there is nothing to do.

**Comment by avishnyakov** [comment]
Indeed, it is. For SSOM it's straightforward, for CSOM we use reflection to figure out if current CSOM assemblies support this prop, and then form CSOM queries.

Could have been old assemblies picked up by VS from the GAC, which didn't have this prop at the time.
