### ISSUE TITLE
Extend SSOM handler for SPList.DisableGridEditing

### ISSUE THREAD

**Issue by andreasblueher** [SubPointSolutions/spmeta2#1097]
I'll create a new pull request to be able to set DisableGridEditing at least for SSOM handler. I know you're not too fond of having to many SSOM only properties, but maybe there will be support for it later down the road when CSOM becomes the no 1 go to choice to automatically deploy models.

**Comment by SubPointSupport** [comment]
Too easy, go ahead.

**Comment by andreasblueher** [comment]
If the PR is merged, can't this issue be closed?

**Comment by SubPointSupport** [comment]
Yes, all good. Closing, implemented in https://github.com/SubPointSolutions/spmeta2/pull/1098 by @andreasblueher
