### ISSUE TITLE
Enhance ContentByQueryWebPartDefinition definition

### ISSUE THREAD

**Issue by avishnyakov** [SubPointSolutions/spmeta2#111]
ItemXslLink and MainXslLink should support ~sitecollection token to simplify provision.
Similar as ContentEditorWebPartDefinition does.

An API for binding should be provided.

* [SSOM/CSOM] Filter1ChainingOperator
* [SSOM/CSOM]  Filter2ChainingOperator
* [SSOM/CSOM]  UseCache
* [SSOM/CSOM]  PlayMediaInBrowser
* [SSOM/CSOM]  CacheXslStorage
* [SSOM/CSOM]  GroupByDirection
* [SSOM/CSOM]  HeaderXslLink
* [SSOM/CSOM]  ShowUntargetedItems
* [SSOM/CSOM]  ListId
* [SSOM/CSOM]  ListsOverride
* [SSOM/CSOM]  ViewFieldsOverride
* [SSOM/CSOM]  FilterByAudience
* [SSOM/CSOM]  CommonViewFields
* [SSOM/CSOM]  QueryOverride
* [SSOM/CSOM]  Filter1ChainingOperator
* [SSOM/CSOM]  Filter2ChainingOperator
* [SSOM/CSOM]  CacheXslTimeOut
* [SSOM/CSOM]  GroupByDirection
* [SSOM/CSOM]  Filter1IsCustomValue
* [SSOM/CSOM]  Filter2IsCustomValue
* [SSOM/CSOM]  Filter3IsCustomValue

The following properties are to be added:
* [SSOM/CSOM] SortBy
* [SSOM/CSOM] SortByDirection
* [SSOM/CSOM] SortByFieldType
* [SSOM/CSOM] ListGuid
* [SSOM/CSOM]  ListUrl
* [SSOM/CSOM]  ListName
* [SSOM/CSOM] WebUrl
* [SSOM/CSOM]  ServerTemplate
* [SSOM/CSOM]  ContentTypeBeginsWithId
* [SSOM/CSOM]  FilterValue1
* [SSOM/CSOM]  FilterValue2
* [SSOM/CSOM]  FilterValue3
* [SSOM/CSOM]  FilterDisplayValue1
* [SSOM/CSOM]  FilterDisplayValue2
* [SSOM/CSOM]  FilterDisplayValue3
* [SSOM/CSOM]  FilterType1
* [SSOM/CSOM]  FilterType2
* [SSOM/CSOM]  FilterType3
* [SSOM/CSOM]  FilterOperator1
* [SSOM/CSOM]  FilterOperator2
* [SSOM/CSOM]  FilterOperator3
* [SSOM/CSOM]  DataMappingViewFields
* [SSOM/CSOM]  DataMappings
* [SSOM/CSOM]  ItemStyle
* [SSOM/CSOM]  UseCopyUtil
* [SSOM/CSOM]  ItemXslLink
* [SSOM/CSOM]  MainXslLink

Regression test should cove various deployment scenarios:
- binding to the list
- binding to the list and content type
- sorting/foltering
- item/main xslt

**Comment by SubPointSupport** [comment]
The following props  are to be added:
* SortBy
* SortByDirection
* SortByFieldType
