### ISSUE TITLE
JobScenariosTest vs JobScenariousTest

### ISSUE THREAD

**Issue by andreasblueher** [SubPointSolutions/spmeta2#1112]
Looking through the Regression scenarios I realized there are 2 files which should do the same thing. Didn't want to delete it by myself. Maybe you can have a look.

namespace SPMeta2.Regression.Tests.Impl.Scenarios

**Comment by SubPointSupport** [comment]
PR merged - https://github.com/SubPointSolutions/spmeta2/pull/1117
Closing this one.
