### ISSUE TITLE
Could not load file or assembly 'Microsoft.SharePoint.Client, Version=15.0.0.0

### ISSUE THREAD

**Issue by Maksim2030** [SubPointSolutions/spmeta2#1129]
### SharePoint API
Which version of SharePoint runtime do you use? 
* O365?

### SPMeta2 API
Latest 1.2.1840.0152

I have error message 
'Could not load file or assembly 'Microsoft.SharePoint.Client, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c' or one of its dependencies. The system cannot find the file specified.'

My version of 'Microsoft.SharePoint.Client' is 16.1.8613.1200. 
I see dependencies 
![image](https://user-images.githubusercontent.com/10229209/53728331-897fc200-3e83-11e9-81e4-c19990a84e77.png)

**Comment by SubPointSupport** [comment]
Hey @IlyeniaMaksim, thanks for raising this.

From what can be seen, we try to setup provision agains O365. Which NuGet package did you use? 
In this case, did you try  `SPMeta2.CSOM.Standard-v16` NuGet package?

It is a bit confusing, but for O365 the following package should be used:
> https://www.nuget.org/packages/SPMeta2.CSOM.Standard-v16/

v16 stands not for SharePoint 2016, it stands for v16 assemblies which was the case for O365 before SP2016 arrival. Now it's a super bit confusing and we will be changing name convention for NuGet packages.

Anyway, check your packages, give it a go and let us know what's happening.

**Comment by Maksim2030** [comment]
I'm using:
![image](https://user-images.githubusercontent.com/10229209/53729746-0eb8a600-3e87-11e9-8421-5a3707a6bd20.png)

**Comment by Maksim2030** [comment]
I'll try it. Thanks!
