### ISSUE TITLE
Site collection creation via CSOM

### ISSUE THREAD

**Issue by JuniorPointer** [SubPointSolutions/spmeta2#1133]
Hello,

I am using a SPMeta2.CSOM.Standard and have a question - is that possible to create site collections via CSOM? Are there any tutorials for SSOM site collection creation?

Thanks in advance!

**Comment by SubPointSupport** [comment]
Hi @JuniorPointer , 

At this moment, SPMeta2 CSOM implementation does not support site collection creation via CSOM.
It uses SharePoint CSOM APIs and unless it is possible to create one via SharePOint API - we can make it supported too.

On-premises, SSOM or PowerShell and SharePoint DSC can be used.
As for SharePoint online (did you mean this option?), we might add this feature.

Closing for the time being, please share your view and anything we can improve.
