### ISSUE TITLE
Add app provisioning support

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#131]
Based on community feedback.
https://subpointsolutions.zendesk.com/entries/93529803-Add-app-provisioning-support

> > I would like to see SPMeta2 include a feature for provisioning apps. I recommend creating a definition (model) for an app, syntax for adding the app to a web model and handlers (CSOM, SSOM) for loading and installing the app.

**Comment by YMIndustries** [comment]
Where can I find the test for this?

**Comment by SubPointSupport** [comment]
The test could be found here:
https://github.com/SubPointSolutions/spmeta2/blob/master/SPMeta2/SPMeta2.Regression.Tests/Impl/Random/RandomDefinitionTest.cs

Definition and model trss is generated by AppDefinitionGenerator here:
https://github.com/SubPointSolutions/spmeta2/blob/master/SPMeta2/SPMeta2.Containers/DefinitionGenerators/AppDefinitionGenerator.cs

AppDefinition should be deployed under web. Also,could be an issues with "apps side loading sharepoint 2013" feature - just check out google for more context.
