### ISSUE TITLE
Adding T4/PS templates for JS vars generation

### ISSUE THREAD

**Issue by avishnyakov** [SubPointSolutions/spmeta2#22]
It would be nice to generate JS vars including fieds ids, names; content type ids, names and the rest so that JS based development would be much easier. It would allow to avoid "copy-paste" id ids/internal names from c# code and model definition to JS files.

**Comment by SubPointSupport** [comment]
Merged with https://github.com/SubPointSolutions/spmeta2/issues/163

**Comment by SubPointSupport** [comment]
Closed. Moved to https://github.com/SubPointSolutions/spmeta2-vsixextensions/issues/15
