### ISSUE TITLE
Cannot add a module file to a newly created content type

### ISSUE THREAD

**Issue by YMIndustries** [SubPointSolutions/spmeta2#290]
Running the code:

```c#
ContentTypeDefinition testContentType = new ContentTypeDefinition
{
	Id = new Guid("{648824F5-1143-4A89-BCE8-908D495D12AA}"),
	Name = "Test Content Type",
	ParentContentTypeId = BuiltInContentTypeId.Item,
	Group = "Tests"
};

ModuleFileDefinition testFile = new ModuleFileDefinition
{
	FileName = "test.txt",

	Content = System.Text.Encoding.Default.GetBytes("test")
};

var model = SPMeta2Model.NewSiteModel()
	.WithContentTypes(contentTypes =>
	{
		contentTypes
			.AddContentType(testContentType, contentType =>
			{
				contentType
					.AddModuleFile(testFile);
			});
	});

var test = new CSOMTestBase();

test.SiteUrl = "https://test.sharepoint.com/sites/test";

test.UserName = "test@test.onmicrosoft.com";
test.UserPassword = "testtest";

test.WithO365Context(test.SiteUrl, context =>
{
	var svc = new CSOMProvisionService();

	svc.DeployModel(SiteModelHost.FromClientContext(context), model);
});
```

results in an error:

> An unhandled exception of type 'Microsoft.SharePoint.Client.PropertyOrFieldNotInitializedException' occurred in Microsoft.SharePoint.Client.Runtime.dll

> Additional information: The property or field 'SchemaXml' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.

on line 47 of SPMeta2.CSOM\ModelHandlers\ContentTypeModelHandler.cs.

Expected result would be for the file to be attached to the content type such that when a list is created using the content type the file shows up in

http://test.sharepoint.com/sites/test/Lists/testList/testContentType/testFile.txt

**Comment by YMIndustries** [comment]
I believe this may be fixed in the latest version, will test.

**Comment by YMIndustries** [comment]
I don't think I can delete this issue, sorry. It's a duplicate of https://github.com/SubPointSolutions/spmeta2/issues/289 and switching to the dev branch fixed it.

**Comment by SubPointSupport** [comment]
No, you cannot delete an issue.
Just mark as closed.
