### ISSUE TITLE
Enhance FarmSolutionDefinition provision

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#324]
SPMeta2 should allow to:
- Provision *.wsp under farm (to all web apps)
- Provision *.wsp under web app (specific to selected app)
- Deploy for the first time, upgrade for the second/etc time

Should be coved with the regression tests.

**Comment by rolandoldengarm** [comment]
Hi, what's the status of this bug? We're currently using SSOM to deploy it, but it's always tricky with single-server vs multi-server environments, so it would be cool if SPMeta2 could handle it.

**Comment by SubPointSupport** [comment]
Guys, not a bug but feature :)

Haven't seen much usage so postponed implementation. What's the target scenario?

**Comment by rolandoldengarm** [comment]
Well, well, the current implementation is: Add a solution if it does not exist (not deploy it); if it exists, upgrade it (which will end up with deployed solution). Of course not intended behavior :)

We're deploying a farm solution, as part of our SPMeta2 deployment. We need a farm solution for feature stapling on MySites. 
Not a big priority, and we've got it working with SSOM. It's a dying part of SharePoint anyway.

**Comment by SubPointSupport** [comment]
Dying? You haven't seen this one yet. SP2010 for a few years. That would be fun for us to get SP2010 CSOM support enhanced.
ContentTypeDefinition should work correctly under SP2010 CSOM #887

Nevertheless, what can we do to improve that solution provision bit?

**Comment by rolandoldengarm** [comment]
When adding a SolutionDefinition to the Farm, it should

- Add and Deploy when not previously deployed.
- Retract, Delete, Add, and Deploy when previously deployed.

That's the basic stuff. Maybe some additional parameters:
- WebApplicationURL's for not-global WSP's
- Allow upgrading (instead of retract, delete, add, deploy) with a parameter

**Comment by SubPointSupport** [comment]
> When adding a SolutionDefinition to the Farm, it should
> * Add and Deploy when not previously deployed.
> * Retract, Delete, Add, and Deploy when previously deployed.
Yes.

> Allow upgrading (instead of retract, delete, add, deploy) with a parameter
Yes.

> WebApplicationURL's for not-global WSP's
No. In that case AddSolution() musg be allowed under web app definition. At least, that how M2 is meant to work. We should not mess up hard-coded URLs and web app resolution into solution deployment. Still thinking about that yet seems to be about right.

**Comment by rolandoldengarm** [comment]
hmm yeah of course. Makes sense.

**Comment by SubPointSupport** [comment]
We'll delay 1.2.90 trying to squeeze this one. Don't seem to have major issues so no rush for the release.

Appreciate your feedback, we'll get there.

**Comment by SubPointSupport** [comment]
In progress. Coming next Monday.

**Comment by SubPointSupport** [comment]
Temporary on hold. Waiting for some other feedback.

**Comment by SubPointSupport** [comment]
@milleraa and @KonstantinKaretnikov, would you please put up a few words on this one?

**Comment by SubPointSupport** [comment]
@rolandoldengarm, a few more comments.
>> Retract, Delete, Add, and Deploy when previously deployed.

Why would we need to retract/delete? Can we go with add/update only?

**Comment by rolandoldengarm** [comment]
nope update is not adding new features / element files, only updating existing artefacts.

**Comment by SubPointSupport** [comment]
Right, noted. Thanks @rolandoldengarm

**Comment by SubPointSupport** [comment]
In work. Adding new functionality, adding some tests. Thank you for the input, guys!

**Comment by milleraa** [comment]
About update:  you can add feature update support to provision new artifacts which were added to new version of wsp. But It is not comfortable to use update only on first phase of project development, we do a lot of redeploying at first phase. And in most cases it is more comfortable to reactivate feature.

**Comment by SubPointSupport** [comment]
Hm.. what exactly do you mean? Install features or something? Any C# examples?

**Comment by milleraa** [comment]
About feature update: 
http://www.sharepointnutsandbolts.com/2010/06/feature-upgrade-part-1-fundamentals.html

But in our projects all features can be just reactivated. Features contain webparts and modules only.

**Comment by SubPointSupport** [comment]
Hell a lot of testing.... thanks but thanks for such a dying feature of SharePoint.

**Comment by SubPointSupport** [comment]
Added new test:
* CanDeploy_FarmSolution_As_Default
* CanDeploy_FarmSolution_As_Deploy
* CanDeploy_FarmSolution_As_Delete
* CanDeploy_FarmSolution_As_Retract
* CanDeploy_FarmSolution_As_Delete_Deploy
* CanDeploy_FarmSolution_As_Retract_Deploy
* CanDeploy_FarmSolution_As_Retract_Delete_Deploy

Further validation, tuning and greens are required.

**Comment by rolandoldengarm** [comment]
`Hell a lot of testing.... thanks but thanks for such a dying feature of SharePoint.`

Sorry 🌹

**Comment by SubPointSupport** [comment]
Haha, it's alright, @rolandoldengarm. We still had to implement a proper *.wsp solution deployment to make metapack work with farm solution and deliver them to the farm

**Comment by SubPointSupport** [comment]
SolutionFarmDefinition how supports  Retract, Delete, Add, Deploy/Update workflows with the ShouldXXX properties.

* ShouldRetract
* ShouldAdd
* ShouldDelete
* ShouldDeploy
* ShouldUpgrade

These are covered by tests under "Regression.Scenarios.FarmSolution"

By default ShouldAdd is always "true"indicate that solution will always be added to the farm. That doesn't mean override, ShouldUpgrade should be used to push a new version of the solution.

DeploymentDate / UpgradeDate are passed to be deployment / upgrade methods. If these are NULLs, then DateTime.Now is used, and M2 waits for the solution deployment / upgrade. If these aren't NULLs, then deployment / upgrade is scheduled for the set time.

The whole workflow looks as following:
* Retract?
* Delete?
* Add?
* Deploy? or Upgrade?

**Comment by rolandoldengarm** [comment]
Nice, good stuff!!

**Comment by rolandoldengarm** [comment]
You're amazing @SubPointSupport .
Just removed all our custom SSOM deployment stuff (which was randomly failing) and just using SPMeta2 and it just works. Going to production next week if all goes well :)

**Comment by SubPointSupport** [comment]
Sounds great. Just play around, make sure it works and covers your scenarios. Before going PROD, of course.

**Comment by rolandoldengarm** [comment]
![image](https://cloud.githubusercontent.com/assets/14539000/19913014/b036f460-a103-11e6-936a-fc0f2992d9af.png)

**Comment by SubPointSupport** [comment]
@milleraa and @KonstantinKaretnikov FYI

**Comment by milleraa** [comment]
Can I use ShouldAdd, ShouldDeploy, ShouldUpgrade in one definition simultaneously to deploy solution if it's not deployed or update if it's already deployed?

**Comment by SubPointSupport** [comment]
@milleraa yes, that is a supported workflow. All would work well.
