### ISSUE TITLE
Improve validation on required properties - enable by default

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#422]
Definition have required properties which always need to be specified. 
Provision does not validate all properties so that null reference exceptions or inability to re-deploy artifacts happens.

There should be a validation process to ensure that required properties are set.
A custom attribute plus validation service will work well.

**Comment by SubPointSupport** [comment]
Most of the definitions' properties were marked with [ExpectRequired] or    [ExpectRequired(GroupName = "XXXXX")] attributes.

[ExpectRequired] represents an independed poperty which needs to be there.
[ExpectRequired(GroupName = "XXXXX")] represents a set of the properties either of each needs to be setup. Logical 'OR' should be used to check is groups is valid.

Second step would introduce pre-deployment service to validate the model tree.

**Comment by SubPointSupport** [comment]
DefaultRequiredPropertiesValidationService is done.

* Result outcome should be implemented
* [ExpectRequired(GroupName = "Web part content")] should be handled appropriately

**Comment by SubPointSupport** [comment]
Implemented as pre-deployment service.

Here is a usage samples:
```
 var provisionService = new SSOMProvisionService();
provisionService.PreDeploymentServices.Add(new DefaultRequiredPropertiesValidationService());

// business as usual
provisionService.DeployModel(..)
```

An instance of DefaultRequiredPropertiesValidationService will be called before model provision, so that it will process the model and throw an exception in case of the missing/incorrect attributes.

Minimal set of attributes is marked with [ExpectRequired] (for single properties) and [ExpectRequired(GroupName = "XXXXX")] for "at least one should be setup". 

DefaultRequiredPropertiesValidationService is included into regression testing so that we have full visibility on required properties for all the definitions.

**Comment by antonkhrit** [comment]
It would be better to have validation enabled by default. But anyway it is good. Than you! We start using soon.
Best regards
Anton Khritonenkov
Plumsail Team
http://plumsail. com


-------- Original Message --------

**Comment by SubPointSupport** [comment]
>>It would be better to have validation enabled by default. 

Afraid of the regression on the already existing project.
A few lines of code to enable this feature is not a dramatic challenge.It keeps everyone safe from the production/legacy failures.

**Comment by antonkhrit** [comment]
Sure, I understood.

Anyway it would be good to consider this for future releases. I mean enabling by default and regression.

Again thank you.
Best regards
Anton Khritonenkov
Plumsail Team
http://plumsail. com


-------- Original Message --------

**Comment by SubPointSupport** [comment]
Should be enabled by default.

**Comment by SubPointSupport** [comment]
DefaultRequiredPropertiesValidationService service is added by default to PreDeploymentServices.
Both CSOM/SSOM provision services inherit ProvisionServiceBase which handles initialisation of the default services.
