### ISSUE TITLE
Enhance 'SSOMProvisionService' with DeployFarmModel/DeployWebApplication extensions

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#441]
Similar to DeploySiteModel/DeployWebModel, a nice shortcut.

**Comment by SubPointSupport** [comment]
Covered with the following extensions:
* SSOMProvisionServiceExtensions.DeployFarmModel()
* SSOMProvisionServiceExtensions.DeployWebApplicationModel()

**Comment by JarNitschar** [comment]
Could you please provide an example how to create a new webapplication?

**Comment by SubPointSupport** [comment]
Sure, tracked here. Thanks for raising that up:
https://github.com/SubPointSolutions/spmeta2-docs/issues/108
