### ISSUE TITLE
Enhance document set API

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#453]
M2 should allow to setup a predefined document set structure:
- default view
- folder structure inside the document type
- default values
- etc

Based on community feedback:
https://www.yammer.com/spmeta2feedback/#/threads/show?threadId=527257927&messageId=527666888

**Comment by jsiegmund** [comment]
Please also include the option to share metadata columns between a document set and the content types in the set.

**Comment by SubPointSupport** [comment]
Thanks fro suggestion, @jsiegmund .

That would be fun - O365 CSOM was recently updated with Document Set API, but onprem CSOM still long way behind. Will see what can we do.

**Comment by baywet** [comment]
We'd be interested in support for document set provisioning, including shared columns, welcome columns and authorized content types. It would be even better if document set templates were inheriting the content types in the definition model, having methods like addlinkedfield(field, bool addToWelcomeView, bool addToSharedColumns...), yammer thread https://www.yammer.com/spmeta2feedback/#/Threads/show?threadId=606122437

**Comment by SubPointSupport** [comment]
Thanks for the additional input, @baywet, appreciate that.
Will see what can be done and will update the ticket accordingly.

**Comment by SubPointSupport** [comment]
Closing this one. Current work is tracked here:
DocumentSet content type settings #1045
