### ISSUE TITLE
Better lookup field provision flow with dependency autodetecting

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#479]
Lookup field provision takes quite an effort to get done.
It would be nice to have a much smoother provision flow and less code. 

Based on the community feeback:
https://www.yammer.com/spmeta2feedback/#/Threads/show?threadId=529743315

>>Jasper Siegmund
I'd say the best option to implement this is to specify or automatically find dependencies in the model and respect them during provisioning. When you determine the sequence in which things are provisioned, it's doable to respect the dependencies.

As for those dependencies, the best thing would be autodetecting them by crosschecking names / id's, but that would be hard. The second best (also fine with me) is to have a property on definitions to indicate a dependency on another definition. That way you could postpone the provisioning of definition x until definition y has been provisioned. Or setting the dependencies in the model can also be an option, although the definition would be conceptually the best place to put it I think.

**Comment by SubPointSupport** [comment]
Can hardly be implemented. Closed until a better way will be found or community demand would require implementation.

**Comment by colindekker** [comment]
Easiest way around this is target your lookups to the masterpage catalog, then just retarget list URLs. This way Fields + ContentTypes stay at site level, lists at web level. OnProvisioned can be leveraged to correct the URLs if needed

**Comment by SubPointSupport** [comment]
That's true. However, we'd still recommend to split up the model into different sub-models to deploy fields, content types, lists and so on, and then leverage ~site/sitecollection tokens to deploy correct lookups.

In that case OnProvisioned event won't be needed so that the model will remain API-independent. Meaning, it won't depend on a custom code AND a particular SharePoint API (such as CSOM/SSOM) so that the model can be deployed with any available provision to any SharePoint.

As for the master page trick, lookup won't update binding if no target list is set. Provision won't fail, it just won't bind lookup field to a list. The second "issue", is that target list URL isn't much "updatable" from the API perspective. It can only be set once and updating it over and over is a challenge.
