### ISSUE TITLE
Add 'PeoplePickerSettingsDefinition' provision

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#514]
#M2 should allow to provision PeoplePickerSettings under the web application.

[DONE] Write generator
[TODO] Write tests

**Comment by andreasblueher** [comment]
This only applies to SSOM as those properties are not available by CSOM and not supported for O365 for obvious reason ;)

**Comment by SubPointSupport** [comment]
Extremely rare case, and you right - only SSOM.

We see hat kind if thing happening while setting up "testing environments".
M2 sometimes is used to set up "random" environment or the environment, say, a container like site//web/list with desired state. Haven't see that for the people picker, yet keen to fill out everything we have in SharePoint, at some point.

**Comment by andreasblueher** [comment]
After looking into this I'm not sure why you assigned the "easy-fix" label here ;-). PeoplePickerSettings is a new definition which has to be created and handeld, in addition to syntax, tests and so on :smile:

**Comment by SubPointSupport** [comment]
Marked as something folks can do. We know some guys who do custom defs, and tests can be on us. That's fine.

But you right, will review easy-fix tag.
