### ISSUE TITLE
WebPartPage provision doesn't work for Office 365 under app permissions (Manage Web)

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#522]
> > SharePoint Online doesn't allow to provision pages with custom content, it throws unauthorized. I'm able to provision other type of files and create wiki page.

https://www.yammer.com/spmeta2feedback/#/Threads/show?threadId=542218251

**Comment by SubPointSupport** [comment]
@antonkhrit is this one still actual?

**Comment by SubPointSupport** [comment]
Closing. Will reopen if needed.

**Comment by antonkhrit** [comment]
Hi,

As it didn't work, we implemented it without SPMeta2. I don't know if it is still actual for someone else.

**Comment by SubPointSupport** [comment]
Thanks! Never had similar requests. We'll reopen later as per customers' feedback.
