### ISSUE TITLE
Enhance 'ListViewDefinition' provision - support 'view style' prop

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#530]
M2 should allow setting up a view style on the list view. 
Needs to be investigated for both CSOM/SSOM.

>>Hi guys, quick question; what's the best approach to deploy somewhat more complicated list views? For instance we have one with a grouping in it, and one which uses the card-based view instead of the default table.

https://www.yammer.com/spmeta2feedback/#/Threads/show?threadId=544649293

SSOM is fine, should be implemented.
CSOM API is limited - https://officespdev.uservoice.com/forums/224641-general/suggestions/8257818-expose-spview-applystyle-method-for-csom

**Comment by SubPointSupport** [comment]
On hold due CSOM API 

http://officespdev.uservoice.com/forums/224641-general/suggestions/8257818-expose-spview-applystyle-method-for-csom

**Comment by SubPointSupport** [comment]
Added BuiltInViewStyleId and SSOM support for list view style.

**Comment by colindekker** [comment]
This is now fixed it seems in CSOM, can it be added there too?

**Comment by SubPointSupport** [comment]
Sorry, @colindekker, could you please elaborate on this?

**Comment by colindekker** [comment]
You can set the listview style id using the following:

```
public static void HandleSetListViewStyle(OnCreatingContext<Web, DefinitionBase> context)
{
  var csomSite = context.Object;

  var actionList = csomSite.Lists.GetByTitle(Lists.ProjectTasks.Title);

  csomSite.Context.Load(actionList, l => l.Fields, l => l.Views, l => l.Id, l => l.Title);
  csomSite.Context.ExecuteQueryRetry(ProcessConstants.RetryMaxCount, ProcessConstants.RetryDelay);

  var view = actionList.Views.Cast<View>().FirstOrDefault(v => v.Title == ListViews.ProjectTasksAll.Title);
  int styleId = 17;

  //parse xml
  XmlDocument doc = new XmlDocument();
  doc.LoadXml(view.ListViewXml);

  XmlElement element = (XmlElement)doc.SelectSingleNode("//View//ViewStyle");
  if (element == null)
  {
    element = doc.CreateElement("ViewStyle");
    element.SetAttribute("ID", styleId.ToString());
    doc.DocumentElement.AppendChild(element);
  }
  else
  {
    element.SetAttribute("ID", styleId.ToString());
  }

  view.ListViewXml = doc.FirstChild.InnerXml;
  view.Update();
  csomSite.Context.ExecuteQueryRetry(ProcessConstants.RetryMaxCount, ProcessConstants.RetryDelay);
}
```
