### ISSUE TITLE
Cover scenarios with ContentByQueryWebPartDefinition

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#535]
Related to the following issues:

#111
#112
#113

>> We want to solve the case  "To show the news from subsite on the parent site."
So, we need to use next scenario for Content Query Web Part:

[DONE] 1. Put CQWP on a Web Part Page 
[DONE] 2. Set parameter "Show items from the following list:" to </site/portal/news/lists/Posts>
[DONE] 3. Set parameter "Show items from this list type:" to <Posts>
[DONE] 5. Set parameter Sort Items by: Published <Descending order>
[DONE] 6. Set parameter "Limit the number of items to display" to "10"
[DONE] 7. Set Styles -Item style to "Title and Description"
[DONE] 10. Set Title of the CQWP to "Latest 10 news"
[DONE] 4. Set additional filters: "Published" <is less than> [Today] and "FinishDate" <is greater than> [Today]
[DONE] 8. Set Title to "Title [Custom Columns];"
[DONE] 9. Set Description to "Published; Number of Likes;"

**Comment by DmitryGuzenko** [comment]
We want to solve the case  "To show the news from subsite on the parent site."
So, we need to use next scenario for Content Query Web Part:
1. Put CQWP on a Web Part Page 
2. Set parameter "Show items from the following list:" to </site/portal/news/lists/Posts>
3. Set parameter "Show items from this list type:" to <Posts>
4. Set additional filters: "Published" <is less than> [Today] and "FinishDate" <is greater than> [Today]
5. Set parameter Sort Items by: Published <Descending order>
6. Set parameter "Limit the number of items to display" to "10"
7. Set Styles -Item style to "Title and Description"
8. Set Title to "Title [Custom Columns];"
9. Set Description to "Published; Number of Likes;"
10. Set Title of the CQWP to "Latest 10 news"

**Comment by SubPointSupport** [comment]
Passed CSOM/SSOM tests for 1. Put CQWP on a Web Part Page 
* CanDeploy_ContentByQueryWebPart_AsIs_BindedToList_ByUrl
* CanDeploy_ContentByQueryWebPart_AsIs_BindedToLibrary_ByUrl

**Comment by SubPointSupport** [comment]
Passed CSOM/SSOM tests for 5. Set parameter Sort Items by: Published 

* CanDeploy_ContentByQueryWebPart_AsIs_With_Sorting

**Comment by SubPointSupport** [comment]
Passed CSOM/SSOM tests for 3. Set parameter "Show items from this list type:" to 
* CanDeploy_ContentByQueryWebPart_AsIs_With_ListTemplateType_AssetLibrary
* CanDeploy_ContentByQueryWebPart_AsIs_With_ListTemplateType_DocumentLibrary
* CanDeploy_ContentByQueryWebPart_AsIs_With_ListTemplateType_GenericList
* CanDeploy_ContentByQueryWebPart_AsIs_With_ListTemplateType_Posts

**Comment by SubPointSupport** [comment]
Passed CSOM/SSOM tests for 6. Set parameter "Limit the number of items to display" to "10"
* CanDeploy_ContentByQueryWebPart_AsIs_With_Limit

**Comment by SubPointSupport** [comment]
Passed Passed CSOM/SSOM tests for 4. Set additional filters: "Published" [Today] and "FinishDate" [Today]
* CanDeploy_ContentByQueryWebPart_AsIs_With_Filters
