### ISSUE TITLE
Enhance XsltListViewWebPartDefinition - add missed XSL* props

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#543]
Add XslLink and other xslt related props.

* [SSOM only] XmlDefinition
* [CSOM/SSOM] XmlDefinitionLink
* [CSOM/SSOM] Xsl
* [CSOM/SSOM] XslLink
* [CSOM/SSOM] GhostedXslLink
* [CSOM/SSOM] DisableSaveAsNewViewButton
* [CSOM/SSOM] DisableViewSelectorMenu
* [CSOM/SSOM] DisableColumnFiltering
* [CSOM/SSOM] InplaceSearchEnabled
* [CSOM/SSOM] BaseXsltHashKey

Based on the following feedback:
* https://www.yammer.com/spmeta2feedback/users/sanjaybhagia-guest#/Threads/fromUser?type=from_user&feedId=1531110572

**Comment by maratbakirov** [comment]
XslLink, GhostedXslLink

**Comment by SubPointSupport** [comment]
Implemented for both CSOM/SSOM. covered by tests under Regression.Scenarios.Webparts.XsltListViewWebPart.XmlAndXslt category:

* CanDeploy_XsltListViewWebPart_WithXmlDefinition
* CanDeploy_XsltListViewWebPart_WithGhostedXslLink
* CanDeploy_XsltListViewWebPart_WithXmlDefinitionLink
* CanDeploy_XsltListViewWebPart_WithXsl
* CanDeploy_XsltListViewWebPart_WithXslLink

However, XmlDefinition setup is not supported via CSOM: 
            * http://officespdev.uservoice.com/forums/224641-general/suggestions/6358731-import-xsltlistviewwebpart-definition
            * http://sharepoint.stackexchange.com/questions/90433/add-document-library-xsltlistviewwebpart-using-csom-or-web-services

**Comment by SubPointSupport** [comment]
Added support for XmlDefinition. Passed CanDeploy_XsltListViewWebPart_WithXmlDefinition() test for CSOM.
