### ISSUE TITLE
http://docs.subpointsolutions.com/spmeta2/how-it-works/

### ISSUE THREAD

**Issue by johnnliu** [SubPointSolutions/spmeta2#554]
http://docs.subpointsolutions.com/spmeta2/how-it-works/ is broken link from https://github.com/SubPointSolutions/spmeta2

**Comment by SubPointSupport** [comment]
Indeed, @johnnliu 

You can use the following one for now, plus we update Git pages - 
http://docs.subpointsolutions.com/spmeta2/

**Comment by SubPointSupport** [comment]
Fixed.
