### ISSUE TITLE
Support "Managed metadata input file format" for the MMS provision

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#568]
M2 should provide support for "Managed metadata input file format".

That would simplify taxonomy provision providing an option to drive it from the OOTB SharePoint csv export.
- https://technet.microsoft.com/en-us/library/ee424396(v=office.14).aspx

Most likely, must be moved to the contrib repository.

**Comment by SubPointSupport** [comment]
@andreasblueher this is something we have been looking into for a long time.

Effectively, parsing SharePoint taxonomy export, crafting M2 model full of terms / groups so on, putting some classic C# unit test for that - bunch of taxonomy exports and then some expected models. 

Nice to have feature, of course. Will be closing this / following week.

**Comment by andreasblueher** [comment]
Looking forward to see your implementation. Had a look at this issue, but didn't feel comfortable ;-). Haven't done much using Managed Metadata myself.

**Comment by SubPointSupport** [comment]
Dropping. Moving to nice-to-have due to lack of popularity.
