### ISSUE TITLE
Can't find model handler for type: [SPMeta2.Standard.Definitions.PublishingPageLayoutDefinitions]

### ISSUE THREAD

**Issue by chara75** [SubPointSolutions/spmeta2#574]
I'm trying to deploy Page Layouts but I get the following error:
{"Value cannot be null.\r\nParameter name: Can't find model handler for type:[SPMeta2.Standard.Definitions.PublishingPageLayoutDefinition]. Current ModelService type: [SPMeta2.CSOM.Services.CSOMProvisionService]."}

I am using the StandardCSOMProvisionService service, but I'm still having issues.  I even tried manually registering the PublishingPageLayoutModelHandler, but I get the same error.

Thanks in advance. (SPMeta2 is an Awesome solution - I really appreciate that you have made it available)

I have included my code below:
        public static void DeployPageLayouts(string siteUrl, string pageLayoutDir, string associatedContentTypeId = _welcomePageContentTypeId)
        {
            var webModel = SPMeta2Model.NewWebModel();
            string[] allPageLayouts = Directory.GetFiles(pageLayoutDir, "*.*", SearchOption.TopDirectoryOnly);
            foreach (string pageLayout in allPageLayouts)
            {
                var pageLayoutDefinition = new PublishingPageLayoutDefinition
                {
                    Title = Path.GetFileNameWithoutExtension(pageLayout),
                    FileName = Path.GetFileName(pageLayout),
                    Content = File.ReadAllText(pageLayout, Encoding.UTF8),
                    AssociatedContentTypeId = BuiltInPublishingContentTypeId.WelcomePage,
                    NeedOverride = true
                };

                webModel.AddHostList(BuiltInListDefinitions.Catalogs.MasterPage, list =>
                {
                    list.AddPublishingPageLayout(pageLayoutDefinition);
                });
            }
            //need to call different service for publishing layouts
            
            Provisioner.DeployPublishingWebModel(siteUrl, webModel);
        }

public static void DeployPublishingWebModel(string url, ModelNode webModel)
        {
            using (SPClient.ClientContext context = new SPClient.ClientContext(url))
            {
                StandardCSOMProvisionService service = new StandardCSOMProvisionService();
                service.RegisterModelHandlers(typeof(PublishingPageLayoutModelHandler).Assembly);
                service.DeployWebModel(context, webModel);

            }
        }

**Comment by chara75** [comment]
I determined my issue.  I had instantiated a CSOMProvisionService in a separate function before this.  So I changed that to a StandardCSOMProvisionService and it fixed the issue.  The handlers might be cached?

**Comment by SubPointSupport** [comment]
CSOMProvisionService works with all "foundation" artifacts, and StandardCSOMProvisionService handles "foundation + standard+" artifacts.

That separation allows people to use M2 for both SharePoint Foundation and Standard, according their needs. If you have any "atandard" artifact in your model - anything related to publishing infrastructure ot taxonomy - you should use StandardCSOMProvisionService.
