### ISSUE TITLE
Add UserDefinition - support adding user to security groups

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#619]
M2 should allow adding users to the security groups.

**Comment by O365Tycho** [comment]
As requested a scenario where this is useful: i have a provisioning app where users fill out a form that triggers a azure webjob that provisions project sites. In the form they can select users to be for example a project manager, project owner etc. I want to add these users to the site during provisioning.

**Comment by SubPointSupport** [comment]
In progress. Adding this week.

**Comment by SubPointSupport** [comment]
Implemented for both CSOM/SSOM. Coveted with the following tests:
* CanDeployRandom_UserDefinition
* CanDeploy_User_UnderGroups_By_Email
* CanDeploy_User_UnderGroups_By_LoginName
