### ISSUE TITLE
Enhance 'TaxononyFieldDefinition' - AnchorId/UseDefaultSiteCollectionTermGroup props

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#676]
AnchorId/UseDefaultSiteCollectionTermGroup props should be added to the field definition.

https://www.yammer.com/spmeta2feedback/#/Threads/show?threadId=591359779

**Comment by maratbakirov** [comment]
Additional investigation have shown that The site collection temgroup is used successfully, but the taxonomy field does not get anchored ... 

Looking more into the code.

**Comment by SubPointSupport** [comment]
How does the model look like? 

Could you please provide more context and the model, so that we will craft a regression test for that?

**Comment by maratbakirov** [comment]
https://github.com/maratbakirov/spmeta2_manual_tests

**Comment by maratbakirov** [comment]
i have tested with IsSiteCollectinGroup = true and with manually propvioding the site colleciton.

**Comment by maratbakirov** [comment]
based what I can see in the spmeta2 code, it should work.
I am using the lates pre release of spmeta2.

**Comment by maratbakirov** [comment]
I have tried to fix it. for some reason in some environemnts the term cannot be found by name query...

**Comment by SubPointSupport** [comment]
Sure, leave it as it is, then. Will take care of the rest.
Many thanks for the effort, @maratbakirov

**Comment by SubPointSupport** [comment]
Closed by @maratbakirov  and #733
