### ISSUE TITLE
Null reference exception when trying to provision taxonomy field with web model

### ISSUE THREAD

**Issue by baywet** [SubPointSolutions/spmeta2#677]
Almost everything is in the title. It causes var context = CurrentSiteModelHost.HostClientContext; line 38 of TaxonomyFieldModelHandler (CSOM) to throw a null reference exception.
It should either be fixed or throw an invalid argument exception when passing webmodel.

The following tests were added:

* CanDeploy_AllFields_UnderSite
* CanDeploy_AllFields_UnderWeb
* CanDeploy_AllFields_UnderList

SSOM gives issues on CanDeploy_AllFields_UnderList for the following cases:
* Formula / Index props are true/toggled for Calculated/MultiChoice field

CSOM give issues on CanDeploy_AllFields_UnderList for the following cases:
* Formula / Index props are true/toggled for Calculated/MultiChoice field
* Indexed = true for ImageFieldDefinition / URLFieldDefinition / LinkFieldDefinition / ComputedFieldDefinition / SummaryLinkFieldDefinition / MediaFieldDefinition / HTMLFieldDefinition / GeolocationFieldDefinition

**Comment by baywet** [comment]
If you want a code to try it out, here it is http://pastebin.com/Y31QJiKn Just replace CSOMProvisionService  by a standard one

**Comment by SubPointSupport** [comment]
FIxed, the following tests were added:

* CanDeploy_AllFields_UnderSite
* CanDeploy_AllFields_UnderWeb
* CanDeploy_AllFields_UnderList

SSOM gives issues on CanDeploy_AllFields_UnderList for the following cases:

Formula / Index props are true/toggled for Calculated/MultiChoice field
CSOM give issues on CanDeploy_AllFields_UnderList for the following cases:

Formula / Index props are true/toggled for Calculated/MultiChoice field
Indexed = true for ImageFieldDefinition / URLFieldDefinition / LinkFieldDefinition / ComputedFieldDefinition / SummaryLinkFieldDefinition / MediaFieldDefinition / HTMLFieldDefinition / GeolocationFieldDefinition
