### ISSUE TITLE
ContentTypeDefinition enhancements - add JSLink

### ISSUE THREAD

**Issue by daveliong** [SubPointSolutions/spmeta2#688]
Hi,

I have a site collection that already has a content type previously deployed as a WSP with feature activation on the content type. The content type is defined on the element.xml file that contains the custom site column fields.
 
I have added a new JSLINK on this existing element xml e.g. 

JSLink="~sitecollection/Style Library/JS/jquery-2.1.1.min.js|~sitecollection/Style Library/JS/TaskTROwnerCloseOut.js">
 
 where the javascript just validates mandatory fields has been entered on the form
 
 So my question how do I use SPMeta2 to just programmatically deploy
 
1) The new TaskTROwnerCloseOut.js javascript file to the style library as ghosted and also 

2) Update the existing content type with JSLINK markup?

Does existing SPMeta2 already has this feature or is it going to be a new feature request in the next release?

Thanks.

Kind regards
David

**Comment by SubPointSupport** [comment]
Hey @daveliong, does SharePoint use JSLink on the content type at all?
Reflection showed that the JSLink prop is not used once it is set on the content type level.

Could you please confirm that it works for you, and what might be a use case to validate that?
Cheers!

**Comment by SubPointSupport** [comment]
@daveliong any updated on the JSLink prop within a content type?
