### ISSUE TITLE
Deserialized models cannot be deployed

### ISSUE THREAD

**Issue by mirontoli** [SubPointSolutions/spmeta2#697]
XML and JSON serialization (ToJSON and ToXML) works fine. Unfortunately deserialiazed models fail while deploying. The InnerException is Object reference not set to an instance of an object. To avoid other variables, this is tested in the same project. Create and deploy model (OK), Serialize model and deserialize model and deploy (Fail).

![deserialized-models-cannot-be-deployed](https://cloud.githubusercontent.com/assets/470105/10379241/a566339a-6e0d-11e5-9eed-ca5bce246a5d.png)

**Comment by SubPointSupport** [comment]
Cheking, thanks!

**Comment by SubPointSupport** [comment]
@mirontoli unfortunately, can't reproduce yet.
Could you please share a model which raises that error? Thanks!

**Comment by SubPointSupport** [comment]
Found, fixed.

Turned out that serialization sets [IgnoreDataMember] props to NULL, so that after serialization all members with  [IgnoreDataMember] attr would be NULL. Including arrays, lists and the rest of the thing you usually set up in the constructor.

The fix is to have a method marked with  [OnDeserialized] attr. That hooks up once deserialization is done so that we have chance to fix up the NULLs and re-init needed props.
  
Testing, the fix will be pushed this Monday to NuGet as -beta.

**Comment by mirontoli** [comment]
Cool! What a quick response!

**Comment by mirontoli** [comment]
Hi, I am sorry, but the issue is still there in 1.2.25-beta2 Here is my model:

```
static void Main(string[] args)
{
    var url = "http://dev.local";
    var original = GetModel();
    var serialized = SPMeta2Model.ToXML(original);
    var deserialized = SPMeta2Model.FromXML(serialized);
    var clientContext = new ClientContext(url);
    var csomProvisionService = new CSOMProvisionService();
    //works
    csomProvisionService.DeployWebModel(clientContext, original);
    //fail
    csomProvisionService.DeployWebModel(clientContext, deserialized);
}
public static WebModelNode GetModel()
{
    var isWebField = new FieldDefinition
    {
        FieldType = BuiltInFieldTypes.Boolean,
        Id = new Guid("{3777CF15-1173-4992-AF06-30DD382E014E}"),
        Title = "Is Web",
        InternalName = "MN_IsWeb",
        Description = "TRUE to configure a site and FALSE for a list or library.",
        DefaultValue = "0",
        AddToDefaultView = true
    };

    var mobileNavigationList = new ListDefinition
    {
        TemplateType = BuiltInListTemplateTypeId.GenericList,
        Title = "MobileNavigation",
        CustomUrl = "MobileNavigation"
    };
    // get fields
    var fields = new List<FieldDefinition>
    {
        isWebField
    };

    //// declare model, eg. bind fields to list
    var model = SPMeta2Model.NewWebModel(web =>
    {
        web.AddList(mobileNavigationList, list =>
        {
            list
                .AddFields(fields);
        });
    });
    return model;
}
```

I cloned the dev branch and debugged. For some reason, in my simple model (one list with one column) DefaultModelTreeTraverseService.Traverse gets hit 21 times (when it works with the original model) and 22 times (with the deserialized model). The caught Exception then is null.

**Comment by SubPointSupport** [comment]
Hello @mirontoli,

Tested your model, confirming that the model correct, both un-derialized and de-serialized models can be deployed, all passes the tests. 

The next step would be double-checking on your side that the latest beta2 release is used, so check typeof(FieldDefinition).Assembly.Location property in the runtime/debug and please let us know what's there.

Cheers!

**Comment by SubPointSupport** [comment]
In addition, we also noticed that your branch is from the M2 master, which is not the latest.

We don't push -beta releases to master updating the master only once per month with the major release. The correct branch for you is the latest M2 dev. Hope that helps too.

**Comment by mirontoli** [comment]
Allright! It works now. I upgraded the SPMeta2 yesterday, but it sill didn't work. Now, the day after, it works, perhaps because I shut down my computer and started again. I should have tried to restart Visual Studio yesterday :)

**Comment by SubPointSupport** [comment]
Thanks! We should start giving a free coffee for folks who found a bug or proved us being wrong :)
