### ISSUE TITLE
Enhance 'ListViewDefinition' - add 'Scope' property

### ISSUE THREAD

**Issue by chara75** [SubPointSolutions/spmeta2#715]
M2 should allow to setup the scope (ViewScope) of the target ListView.
As per the community feedback:

>> I want to create a list view with a Scope of Recursive (need to see all files that are in subfolders without the folder in the view).  However, it looks like the Scope property in ListViewDefinition is not available (v1.2.2).  Is there another way to do this?

Thanks!

**Comment by SubPointSupport** [comment]
Thanks for letting know, @chara75 

The ViewXml might allow to define the scope, confirming that scenarios and will get back to you soon.

**Comment by SubPointSupport** [comment]
Will add 'Scope' prop to the ListDefinition. Thanks for bringing that up, @chara75

**Comment by SubPointSupport** [comment]
implemented, will be pushed with 1.2.35-beta1 next week.

**Comment by chara75** [comment]
Oh wow, thanks for such a quick answer and action!!  You rock!  I did find some other minor things that I worked around by extending your classes.  I'll post it in another issue in case it helps you or others.

**Comment by SubPointSupport** [comment]
No worries.

What are they? Would you like to start off a discussion at Yammer? - https://www.yammer.com/spmeta2feedback
>> I did find some other minor things that I worked around by extending your classes
