### ISSUE TITLE
Cannot find Model Handler for ContentBySearchWebPartDefinition

### ISSUE THREAD

**Issue by mirontoli** [SubPointSolutions/spmeta2#722]
ContentBySearchWebPart cannot be deployed:

{"Value cannot be null.\r\nParameter name: Can't find model handler for type:[SPMeta2.Standard.Definitions.Webparts.ContentBySearchWebPartDefinition]. Current ModelService type: [SPMeta2.CSOM.Services.CSOMProvisionService]."}

InnerException.StackTrace: 

   at SPMeta2.Services.ModelServiceBase.ResolveModelHandlerForNode(ModelNode modelNode)
   at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)

```C#
public static ContentBySearchWebPartDefinition PictureResults = new ContentBySearchWebPartDefinition
{
    Title = "Picture Results",
    Id = "PictureResultsWebPart",
    ZoneId = "Main",
    ZoneIndex = 10,
    ChromeType = BuiltInPartChromeType.None,
};
```

**Comment by SubPointSupport** [comment]
Change CSOMProvisionService -> StandardCSOMProvisionService.

* CSOMProvisionService goes with foundaiton.
* StandardCSOMProvisionService goes with SP standard+ artifacts.

**Comment by mirontoli** [comment]
Correct. Thank you!
