### ISSUE TITLE
System.MissingField exception on instantiate CSOMProvisionService

### ISSUE THREAD

**Issue by jeanluc33** [SubPointSolutions/spmeta2#723]
On update from 1.2.20 to 1.2.30.  

Reverted to 1.2.20 and works fine.

![screen shot 2015-10-27 at 3 50 51 pm](https://cloud.githubusercontent.com/assets/13701716/10770790/8be3a5b4-7cc3-11e5-8a52-705762cc53e4.png)
![screen shot 2015-10-27 at 3 51 01 pm](https://cloud.githubusercontent.com/assets/13701716/10770792/90d5069e-7cc3-11e5-9848-48facb6e7f66.png)

**Comment by SubPointSupport** [comment]
Old version in the GAC?
Would you pls double check it?

**Comment by SubPointSupport** [comment]
Hi @jeanluc33, 
Any luck of the GAC?

**Comment by jeanluc33** [comment]
Yes, this was a GAC issue.  Sorry missed response.

**Comment by SubPointSupport** [comment]
Thanks!
