### ISSUE TITLE
Enhance 'ContentTypeDefinition' provision - add parent content type name prop

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#737]
It would be nice if M2 has parent content type name prop. In some scenarios only a content type name is known, not the ID. 

```
In my scenario I only know the name of the content type. Id may differ between environments. That's why I think it would be good to have an option to provide parent content type name, not Id, when specifying ContentTypeDefinition instance.
```

https://www.yammer.com/spmeta2feedback/#/Threads/show?threadId=611988702

[DONE] Implementation - https://github.com/SubPointSolutions/spmeta2/pull/782
[DONE] Merge
[DONE] Regresion tests

**Comment by andreasblueher** [comment]
I would like to implement this enhancement, however I'm not 100% sure on how you wanted to achieve this change. If no parent content type id is provided but a name, would you search for a site content type with the given name and use it's content type id?

**Comment by SubPointSupport** [comment]
Indeed. ContentTypeId takes priority, the ContentTypeName is a fall back in case ContentTypeId  has not been provided and the resolution should work by name.

Resolution by name simplifies scenarios where M2 models work with the 'already excising stuff created by users'. Not a common scenarios, yet nice to have.

**Comment by andreasblueher** [comment]
Alright and is there a reason why you don't specify ParentContenttype when creating a new ct in SSOM? Does SharePoint through merged content type id recognize which parent it is?

**Comment by SubPointSupport** [comment]
Exactly, it recognizes the parent by the ID lookup.
