### ISSUE TITLE
Add detection of CSOM/SSOM support of the target model

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#750]
Model can have some definitions unsupported by CSOM. There should be a way to detect these defs and nodes.

That would enable validation on CSOM/O365 compatibility as well as better 3rd part tooling support.

**Comment by andreasblueher** [comment]
Do you have any idea on how this could be implemented? As discussed in yammer I like the idea and would like to have something like that for M2

**Comment by SubPointSupport** [comment]
The folllwing test were added:
* Should_Pass_On_Valid_SSOM_CSOM
* Should_Pass_On_Valid_SSOM_Invalid_CSOM
* Should_Pass_On_Valid_SSOM_Invalid_CSOM_2

The following API was added:
* SPMeta2Model.IsCSOMCompatible(model)
* SPMeta2Model.IsSSOMCompatible(model)
* SPMeta2Model.CheckProvisionCompatibility(model)
