### ISSUE TITLE
Add List.IndexedRootFolderPropertyKeys provision support 

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#778]
Similar to Add Web.IndexedPropertyKeys provision support #749 - at the list level.

https://samlman.wordpress.com/2015/03/01/searching-property-bags-in-sharepoint-2013/

**Comment by andreasblueher** [comment]
If this is merged, you can close this issue right?

**Comment by SubPointSupport** [comment]
Yes, merged. "Todo" for us to write tests.
