### ISSUE TITLE
Enhance ListItemDefinition to support CSOM thresholds 

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#784]
CSOm implementation for theListItemDefinition does not support larger lists.
A threshold exception is raised. Must be improved.

Based on the community feedback:
https://www.yammer.com/spmeta2feedback/#/Threads/show?threadId=653868669

**Comment by andreasblueher** [comment]
I just tried out something here, but in the end I failed to reproduce the threshold exception. Even with 30000 items, reduced threshold and everything my console application was able to return all items or a single one without any issues.

My solution is using ListItemCollectionPosition just like PnP is doing it in their example https://github.com/OfficeDev/PnP/tree/master/Samples/Core.ListViewThreshold .

On the other side I would raise the question if you really should support larger lists, if you query the whole list for each ListItemDefinition there is. Performance wise this gets worse with every new item, if the column isn't indexed.

Wether you/I fix this error, that GetItems you're using inside "FindListItem" should contain RowLimit = 1 so whenever you find one, you stop searching.

**Comment by SubPointSupport** [comment]
Did you use admin / farm account, it could be site admin / web admin who does not have same permissions to get all items.

Our first impl was to get thing up and running, both csom and ssom were never polished. Should be improved  as you mentioned.

**Comment by SubPointSupport** [comment]
Untested, postponing unless an urgent fix is required. 

Most likely, both CSOM/SSOM will fail over large lists. M2 is usually used for the initial provision or upgrade so that such cases with the large lists are extremely rare.

**Comment by SubPointSupport** [comment]
Dropped. Cannot replicate the issue. Won't fix until a strong business case is presented.
