### ISSUE TITLE
Provisioning publishing page throws null reference exception

### ISSUE THREAD

**Issue by leolorenzoluis** [SubPointSolutions/spmeta2#788]
Running the given example from [here](http://docs.subpointsolutions.com/spmeta2/definitions/sharepoint-standard/PublishingPageDefinition/#Adding with custom layout)

```
var customPublishing = new PublishingPageDefinition
    {
        Title = "Custom publishing",
        FileName = "Custom-publishing.aspx",
        PageLayoutFileName = "__ specify a publishing page layout file name here ___"
    };
 
    var model = SPMeta2Model.NewWebModel(web =>
    {
        web.AddHostList(BuiltInListDefinitions.Pages, list =>
        {
            list
                .AddPublishingPage(customPublishing);
        });
    });
```

throws an exception

> SPMeta2.Exceptions.SPMeta2ModelDeploymentException: There was an error while pro
visioning definition. Check ModelNode prop. ---> System.NullReferenceException:
Object reference not set to an instance of an object.
   at SPMeta2.SSOM.Standard.ModelHandlers.PublishingPageModelHandler.<>c__Displa
yClass8.<DeployPublishingPage>b__7(SPFile afterFile)
   at SPMeta2.SSOM.ModelHandlers.ModuleFileModelHandler.WithSafeFileOperation(SP
List list, SPFolder folder, String fileUrl, String fileName, Byte[] fileContent,
 Boolean overide, Action`1 onBeforeAction, Action`1 onAction)
   at SPMeta2.SSOM.Standard.ModelHandlers.PublishingPageModelHandler.DeployPubli
shingPage(Object modelHost, SPList list, SPFolder folder, PublishingPageDefiniti
on publishingPageModel)
   at SPMeta2.SSOM.Standard.ModelHandlers.PublishingPageModelHandler.DeployModel
(Object modelHost, DefinitionBase model)
   at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object mode
lHost, ModelNode modelNode)
   --- End of inner exception stack trace ---
   at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object mode
lHost, ModelNode modelNode)
   at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.<>c__DisplayClass6.<
Traverse>b__4(Object childModelHost)
   at SPMeta2.SSOM.ModelHandlers.ListModelHandler.WithResolvingModelHost(ModelHo
stResolveContext modelHostContext)
   at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object mode
lHost, ModelNode modelNode)
   at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.<>c__DisplayClass6.<
Traverse>b__4(Object childModelHost)
   at SPMeta2.SSOM.ModelHandlers.WebModelHandler.WithResolvingModelHost(ModelHos
tResolveContext modelHostContext)
   at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object mode
lHost, ModelNode modelNode)
   at SPMeta2.Services.ModelServiceBase.ProcessModelDeployment(Object modelHost,
 ModelNode modelNode)
   at SPMeta2.Services.ModelServiceBase.DeployModel(ModelHostBase modelHost, Mod
elNode model)
   at SPMeta2.SSOM.Services.SSOMProvisionService.DeployModel(ModelHostBase model
Host, ModelNode model)
   at SPMeta2.SSOM.Services.SSOMProvisionServiceExtensions.DeployWebModel(SSOMPr
ovisionService modelHost, SPWeb web, ModelNode model)

**Comment by SubPointSupport** [comment]
Thanks for reporting that. Which version of m2 did you use?

**Comment by SubPointSupport** [comment]
Did you provide PageLayoutFileName for the page definition, which one?

**Comment by leolorenzoluis** [comment]
I did. I missed the extension file name of the file. 

I had to do something like "PageLayout.aspx". I was expecting ".aspx" is taken care for me. Assuming I didn't provide the file extension, then the wrapper model should take care of it. It is most likely a page layout template that is being used and will end with ".aspx" and it can't be .html or any other file extension. Unless I am missing a different use case?

**Comment by SubPointSupport** [comment]
Valid point. We'll add a validation on top, so that M2 won't allow to provision a model without PageLayoutFileName set, and will also validate the extension - it must end with ".aspx" which makes sense.

Will do, thanks for the suggestion, @leolorenzoluis 
https://github.com/SubPointSolutions/spmeta2/issues/791
