### ISSUE TITLE
Provision Empty Quick Launch on SPWeb

### ISSUE THREAD

**Issue by leolorenzoluis** [SubPointSolutions/spmeta2#789]
Is there a way to provision quick launch that doesn't provide SharePoint default quick launch? For example, I provision a blank site and when I try to add quick launch definitions, I don't want it to add on top of the default built in ones like `Libraries, Discussion, Lists`. 

The current work around for me right now is to manually create the SPWeb and delete quick launch nodes, then use SPMeta2 to provision other stuff. I didn't want to use AddWeb definition because it is expensive to create new context for each SPWeb, so I might as well handle it by myself. I think it would be nice if there's a property in the WebDefinition that would define if use empty quick launch by default?

**Comment by SubPointSupport** [comment]
@leolorenzoluis not too sure we understand you.

Is that correct that the goal is to clean up already existing quick launch nodes, and then add yours on top? So that the question is now to "clean up" or "remove" already quick  launch nodes?

**Comment by SubPointSupport** [comment]
Also, if there are more questions or suggestions, don't hesitate to join M2 Yammer Network here:
https://www.yammer.com/spmeta2feedback/#/threads/inGroup?type=in_group&feedId=4881224

**Comment by leolorenzoluis** [comment]
Yes, I need a way to clean up or remove quick launch nodes.

**Comment by SubPointSupport** [comment]
Unsupported right now. A custom code, prior/post the M2 deployment might be an option.

M2 tends to avoid any "deleting" activities to prevent potential data losses and other library "mis-usage" risks which eventually raise the data losses / data corruption. M2 goes "create or update, never delete" (apart a few definitions).

We see some deleting / retracting implementation happening, yet it wasn't planned out.

**Comment by leolorenzoluis** [comment]
There shouldn't be any data losses/data corruption if it is just Quick Launch model? I understand that this is a weird use case. I just wanted to automate everything using SPMeta since it does the guard checks for me. What are the few definitions that "deletes"?

**Comment by SubPointSupport** [comment]
The following defs have "deleting" affect:

* CSOM provision always deletes web parts and then adds new
* DeleteWebPartDefinition is meant to provide clean up mechanism for the pages

Understand the desire and nav links retraction was asked early by other people, will see how we can address that.
