### ISSUE TITLE
Provisioning SecurityGroupDefinition fails

### ISSUE THREAD

**Issue by leolorenzoluis** [SubPointSolutions/spmeta2#790]
I'm trying to provision security groups in SharePoint 2010 but it failed with an exception

`Check ModelNode prop`

Using the following code found [here](http://docs.subpointsolutions.com/spmeta2/definitions/sharepoint-foundation/SecurityGroupDefinition/#Adding security group)

```
public void CanDeploySimpleSecurityGroup()
{
    var auditors = new SecurityGroupDefinition
    {
        Name = "External Auditors",
        Description = "External auditors group."
    };
 
    var reviewers = new SecurityGroupDefinition
    {
        Name = "External Reviewers",
        Description = "External reviewers group."
    };
 
    var model = SPMeta2Model.NewSiteModel(site =>
    {
        site
            .AddSecurityGroup(auditors)
            .AddSecurityGroup(reviewers);
    });
 
    DeployModel(model);
}
```

I'm using the latest version of M2.

**Comment by SubPointSupport** [comment]
The model looks good, should be fine.

Would you please provide .InnerException message? M2 exception has .InnerException that contains original SharePoint exception. That would help to address the issue.

**Comment by leolorenzoluis** [comment]
Here's the complete stack trace

`   at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)
   at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.<>c__DisplayClass6.<Traverse>b__4(Object childModelHost)
   at SPMeta2.ModelHandlers.ModelHandlerBase.WithResolvingModelHost(ModelHostResolveContext context)
   at SPMeta2.SSOM.ModelHandlers.SiteModelHandler.WithResolvingModelHost(ModelHostResolveContext context)
   at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)
   at SPMeta2.Services.ModelServiceBase.ProcessModelDeployment(Object modelHost, ModelNode modelNode)
   at SPMeta2.Services.ModelServiceBase.DeployModel(ModelHostBase modelHost, ModelNode model)
   at SPMeta2.SSOM.Services.SSOMProvisionService.DeployModel(ModelHostBase modelHost, ModelNode model)
   at SPMeta2.SSOM.Services.SSOMProvisionServiceExtensions.DeployWebModel(SSOMProvisionService modelHost, SPWeb web, ModelNode model)`

**Comment by SubPointSupport** [comment]
Alright, leave it with us, will see what's wrong there.

We run regression testing on SP2013 only. 
SP2010 is only compiled with NET35 and SP2010 assemblies, haven't seen great utilization so never focused on regression there. ETA would be a week or so, will update the ticket accordingly.

**Comment by leolorenzoluis** [comment]
Thank you. By the way, I also tried adding `Owner, DefaultUser` too. I assume those were the required fields in order to provision a SecurityGroup in SPOM.

**Comment by SubPointSupport** [comment]
No, only props with ExpectRequired attr are required.
In case security group, Name prop is the only required prop.

**Comment by SubPointSupport** [comment]
Checked on SharePoint 2010, all good.

Security groups deployment is only supported at the site level. Here is the full snippet:
```cs
public void CanDeploySimpleSecurityGroup()
{
    var auditors = new SecurityGroupDefinition
    {
        Name = "External Auditors",
        Description = "External auditors group."
    };

    var reviewers = new SecurityGroupDefinition
    {
        Name = "External Reviewers",
        Description = "External reviewers group."
    };

    var model = SPMeta2Model.NewSiteModel(site =>
    {
        site
            .AddSecurityGroup(auditors)
            .AddSecurityGroup(reviewers);
    });

    DeployModel(model);
}

private void DeployModel(ModelNode model)
        {
            var service = new SSOMProvisionService();

            using (var spSite = new SPSite("http://m2-sp10-01"))
            {
                using (var spWeb = spSite.OpenWeb())
                {
                    service.DeploySiteModel(spSite, model);
                }
            }
        }
```

With service.DeployWebModel(spWeb , model); call a new SPMeta2UnsupportedModelHostException exception is raised which is default expected behavior.
```
SPMeta2.Exceptions.SPMeta2ModelDeploymentException: There was an error while provisioning definition. Check ModelNode prop. ---> SPMeta2.Exceptions.SPMeta2UnsupportedModelHostException: modelHost
Result StackTrace:	
```
