### ISSUE TITLE
Incomplete handling of SPList UniqueContentTypeOrder

### ISSUE THREAD

**Issue by sebastianmattar** [SubPointSolutions/spmeta2#794]
AddUniqueContentTypeOrder() misses a way to remove entries from the UniqueContentTypeOrder property. The current implementation only adds and reorders Content Types.

I propose to change the implementation so that Content Types that are not contained in the UniqueContentTypeOrderDefinition will be removed.

**Comment by SubPointSupport** [comment]
Well, there are HideContentTypeLinksDefinition and RemoveContentTypeLinksDefinition, these can be paired with UniqueContentTypeOrderDefinition to get desired content types within a list.

Would it solve the case you are after?
What's missed?

**Comment by sebastianmattar** [comment]
You are right, this is exactly what I was missing. Thank you!

**Comment by SubPointSupport** [comment]
Not a problem, thanks for bringing that up.
