### ISSUE TITLE
QuickLaunchNavigationNodeDefinition doesn't add/update quick existing site

### ISSUE THREAD

**Issue by leolorenzoluis** [SubPointSolutions/spmeta2#802]
Using latest version of M2, and running the following code

    var employeeHandbook = new QuickLaunchNavigationNodeDefinition
                    {
                        Title = "Employee Handbook",
                        Url = "/Handbook/Pages/Introduction.aspx",
                        IsExternal = true
                    };

    var training = new QuickLaunchNavigationNodeDefinition
                    {
                        Title = "Training",
                        Url = "/Training/Pages/Home.aspx",
                        IsExternal = true
                    };
    web.AddQuickLaunchNavigationNodes(new[]
                        {employeeHandbook, training});

where /Handbook and /Training are subsites of the root site collection, it doesn't add or update the quick launch with the subsite links. It only updates the links existed within its own subsite. Also tried setting IsExternal to true/false.

I suspect that because the subsites already exists and it is checking against the URL, technically the URL already exists if "Show subsites" is enabled, so that's why it is not adding it.

**Comment by SubPointSupport** [comment]
Hm.. an interesting one. 

SP2010 / 2013 / O365? CSOM / SSOM?
Is publishing infrastructure enabled?

Top/QuickLaunchNodeDefinition support ~sitecollection/~site tokens for better URL resolution
https://github.com/SubPointSolutions/spmeta2/issues/448

Give a shot with the following one:
```
var training = new QuickLaunchNavigationNodeDefinition
                {
                    Title = "Training",
                    Url = "~sitecollection/Training/Pages/Home.aspx",
                    IsExternal = true
                };
``

**Comment by SubPointSupport** [comment]
Closing unless suggested solution is validated by @leolorenzoluis
