### ISSUE TITLE
Add DeleteTopNavigationNodesDefinition / DeleteQuickLaunchNavigationNodesDefinition to delete navigation nodes

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#804]
M2 should be able to hide / delete quick and top navigation nodes based on criteria:
* all of them
* some of them by Title or Url match

This feature was highly desired by the community. Should be implemented in the first place.

**Comment by MarkusJenni** [comment]
Because the IsVisible property does not work as expected because of a SharePoint bug, an easy way to remove Navigation nodes by Title or Url match would be a modification of QuickLaunchNavigationNodeModelHandler: Instead of setting the IsVisible property to false, we could remove the navigation node.

**Comment by SubPointSupport** [comment]
Thanks for the input, @MarkusJenni.

We'll go with a new definition similar to DeleteWebPartsDefinition. The goal is to separate deleting operation avoiding mixing up creation / update process and potential data losses. M2 always creates or updates stuff, deleting is extremely rare.

**Comment by SubPointSupport** [comment]
As IsVisible property does not work properly due to SharePoint bug, a workaround should be considered:

* Emulate IsVisible property via available means, is possible
* Delete the whole link (not a great idea, as it would loose the ordering over the next deployment)
* Consider a new definition to implement "delete" operation due to lack of "visibility" change
* Consider setting a fake audience as SharePoint group so that the link would not pop up (oh boy, just adding an idea)
 
* http://stackoverflow.com/questions/2624258/spnavigationnode-isvisible-property-not-working-in-sharepoint-as-expected

**Comment by SubPointSupport** [comment]
Added DeleteTopNavigationNodesDefinition / DeleteQuickLaunchNavigationNodesDefinition.
Implemented for both CSOM/SSOM, covered by the following tests:

* CanDeployRandom_DeleteTopNavigationNodesDefinition
* CanDeploy_DeleteTopNavigationNodes_ByTitle
* CanDeploy_DeleteTopNavigationNodes_ByUrl
* CanDeploy_DeleteTopNavigationNodes_ByTitleAndUrl
* CanDeployRandom_DeleteQuickLaunchNavigationNodesDefinition
* CanDeploy_DeleteQuickLaunchNavigationNodes_ByTitle
* CanDeploy_DeleteQuickLaunchNavigationNodes_ByUrl
* CanDeploy_DeleteQuickLaunchNavigationNodes_ByTitleAndUrl

**Comment by babakb** [comment]
Hi
Just wondering which version have this class "DeleteQuickLaunchNavigationNodesDefinition" ?

**Comment by SubPointSupport** [comment]
Upcoming 1.2.70
Will also include a list of all definitions per version, here is a ticket: https://github.com/SubPointSolutions/spmeta2/issues/846

**Comment by babakb** [comment]
Cool, when do you think it will be published?

**Comment by SubPointSupport** [comment]
Over the weekend or Monday. Testing internally.

What are the scenarios you are looking for?

**Comment by babakb** [comment]
Just want to hide/remove some OOTB navigation from Quick lunch and as the rest of project is on SPMeta2 don't want to use CSOM.

**Comment by babakb** [comment]
Hi again. I've tested DeleteQuickLaunchNavigationNodesDefinition class with my scenario from your dev branch and it's working fine. I removed all OOTB navigation and added new ones. just waiting for a published version (1.2.7)

**Comment by SubPointSupport** [comment]
Thanks @babakb, appreciate your feedback.

Curious on the particular OOTB nodes in your scenarios. What are they? Would you please provide more context, so that we would add this case in the regression tests as well.

Next, we aren't sure how to get the right deleting experience for the 2nd/3rd navigation nodes. Current implementation works well for the 1st level only. Guess, will leave it as it is for the time being until the community asks for more cases.

1.2.7 is being tested, delaying. Current dev is stable for both CSOM/SSOM.

**Comment by babakb** [comment]
I'm using it for project sites on project online. they have a few default navigation (Notebook-Documents-Tasks-Calendar-Projects-Project details) which in our scenario should be removed. they are all 1st level navigation nodes.

Just as a sample :

static DeleteQuickLaunchNavigationNodesDefinition OOTBNotebook = new DeleteQuickLaunchNavigationNodesDefinition
        {NavigationNodes = new List<NavigationNodeMatch>() { new NavigationNodeMatch(){Title= "Notebook",}}};
 var projectWebModel = SPMeta2Model.NewWebModel(web =>
            {web.AddDeleteQuickLaunchNavigationNodes(OOTBNotebook)});
var csomProvisionService = new StandardCSOMProvisionService();
csomProvisionService.DeployWebModel(projectSiteClientContext, projectWebModel);

**Comment by SubPointSupport** [comment]
Right, makes perfect sense. Thank you for sharing that.

**Comment by babakb** [comment]
Any update on publishing version 1.2.7?
