### ISSUE TITLE
Adding target audience in WebParts

### ISSUE THREAD

**Issue by leolorenzoluis** [SubPointSolutions/spmeta2#806]
How do you add target audience in webparts? I don't seem to find an extension for `AddSecurityGroupLink`?

**Comment by SubPointSupport** [comment]
Unsupported at this moment. 
You either can modify web part xml prior deployment in csom or get an instance if the webpart in ssom to assign correct audience settings.

We'll have a look abs get back with that one. Thanks for bringing that up.

**Comment by SubPointSupport** [comment]
Related to Enhance web part provision - add audience targeting support #517 
Closing thins one as a duplicate, please put comment or more input on #517
