### ISSUE TITLE
Provision Quick Launch

### ISSUE THREAD

**Issue by leolorenzoluis** [SubPointSolutions/spmeta2#817]
When provisioning quick launch, is there a way for me to create an item that doesn't have a URL.

In other words, when I go to site settings -> navigation -> create a heading. How do I achieve that in spmeta2?

**Comment by SubPointSupport** [comment]
Most likely unsupported yet, a custom code is a recommended approach for the time being.

The thing is that such navigation seems to be part of the publishing infrastructure (hence standard+ SharePoint API). In turn, that would not fit well into existing definition - in one case we'd like to have a link, in other - a heading.

Having said that, we think to introduce additional property to the navigation definitions to indicate that it should be a heading. Would that work well for your case, @leolorenzoluis?

**Comment by leolorenzoluis** [comment]
Yes, just a property that indicates this will be header would be great.

**Comment by SubPointSupport** [comment]
Added new ticked, closing this one.
https://github.com/SubPointSolutions/spmeta2/issues/818
