### ISSUE TITLE
Provision a publishing page that doesn't inherit in Master Page

### ISSUE THREAD

**Issue by leolorenzoluis** [SubPointSolutions/spmeta2#833]
Is there a way to provision a publishing page without inheriting in Master Page? So I basically want my own html file and that's it. No SharePoint add-ins.

**Comment by SubPointSupport** [comment]
Hello @leolorenzoluis 

Not too sure how it would be possible at all. 
If this is a publishing page, well then you can craft a custom publishing page layout and then create your page with mentioned custom page layout. That will do, and fully support by M2.

If the intention is just to bring an HTML file, then module file can also be used as well.

Let us know if this solves your case, and if there is other things we can help you with.

**Comment by SubPointSupport** [comment]
@leolorenzoluis, we are closing this ticket. Let us know if there is anything else we can hep.
