### ISSUE TITLE
ChangedItemProperties not saved by SP after provisioning

### ISSUE THREAD

**Issue by achappey** [SubPointSolutions/spmeta2#856]
Hello,
When I provision a subsite in a RER ItemAdding Event, provisioning works well. No exceptions. 
But the properties sent back to SharePoint in the ChangedItemProperties collection of the RemoteEventResult object are not saved by SP.
No exception, but no updated properties either.

When I provision with manual CSOM code everything works well. Maybe I do miss something?
I use the provisioner in AppEvents en WebJobs too, without a hassle. Keep up the good work!

**Comment by SubPointSupport** [comment]
Hey @achappey, many thanks for reperting this. Appreciate your time.

Interesting and intriguing case with RER. We do utilise the same API, same CSOM as you. No too sure is that related to M2, frankly saying.

Does that happen on "small" models? Say one web site or one list, or something light, something what does not take much time and resources to be provisioned? Would you please give a try with one list, something really small to see if that issue still persists?

**Comment by SubPointSupport** [comment]
Also, thanks for the warm words on M2. 
Anyting else we might improve? Anything you found particular exciting or challenging?

Btw, we have a Yammer network, just in case:
https://www.yammer.com/spmeta2feedback

**Comment by achappey** [comment]
Thanks for the quick reply. Was a couple of days ago and it kept me busy for couple of hours, so not sure anymore what minimal prov. I tried. Will try again with minimal code and let you know

**Comment by SubPointSupport** [comment]
Thanks! That's be really great. Looking forward to hear more details.

**Comment by achappey** [comment]
Hi,
I've setup an empty project with minimal stuff to get this reproduced.
Wasn't easy, because I couldn't get clear what the wrong part is. Seem like a combination of something.

What happens:
- App installed event creates 1 parent content type, 2 child content types
- App installed event creates 1 list 
- App installed event binds ItemAdding to this list

```
     var siteModel = SPMeta2Model.NewSiteModel(site =>
     {
        site.AddContentType(ParentCustomContentType);
        site.AddContentType(CustomContentType);
        site.AddContentType(Custom2ContentType);
     });

     var model = SPMeta2Model.NewWebModel(site =>
     {
        site.AddList(new SPMeta2.Definitions.ListDefinition()
        {
           Title = "Test List",
           TemplateType = BuiltInListTemplateTypeId.GenericList,
           CustomUrl = "TestList"
        });
     });

     var csomProvisionService = new CSOMProvisionService();
     csomProvisionService.DeploySiteModel(clientContext, siteModel);
     csomProvisionService.DeployWebModel(clientContext, model);

```
On ItemAdding a subsite is created and provisioned with:
- 1 Custom List with a custom column
- 1 Document Library with a couple of custom Content Type Bindings
- When done provisioning, the Title property is added to the ChangedItemProperties.

`
result.ChangedItemProperties.Add("Title", "Site Created");
`
 
For simplicity I used some default document content types and have put all custom code the AppEventReceiver.cs.
I would expect Item title to be Site Created but it ends up with inserted title.

Hope you can see where things go wrong! Drivin me a bit crazy :)
Full code here: **https://github.com/achappey/rertest**

**Comment by SubPointSupport** [comment]
@achappey oh boy, that does indeed sounds like fun.

First of all, appreciate our time and effort on getting to the root of the problem. We'll start looking into that. Would take some time due to the edge case scenario and some setup required. 

Have you found a work around yet? How critial is that issue?

**Comment by achappey** [comment]
Ok, cool. Appreciate it and hope you can solve it. This is really the easiest scenario I could create to reproduce. When, for the example, the custom list on the subweb isn't created, everything goes fine. But it's unpredictable, that makes it hard.

My problem is that I need to redirect users to the newly created site that has a landing page (and document) with columns coming from one of those content types.

Think I can move some provisioning to itemadded and add some javascript before redirect as workaround. Not worked on it yet, it's part of a bigger project, so not a real hurry.
Thanks for the efforts!

**Comment by achappey** [comment]
Hi,
Just a message to let you know I found a permanent solution for this. Create some temporary sites on site collection provisioning, just some rename stuff in ItemAdding and a new temp site in ItemAdded. UX is better anyway with the quicker redirects!

**Comment by SubPointSupport** [comment]
@achappey, thank you for sharing the workaround. We'll put it on hold then as there is a workaround, the whole case is a bit rare and has not been reported by other folks. Low priority unless more reports come across.

**Comment by SubPointSupport** [comment]
Closing unless a further assistance is required.
