### ISSUE TITLE
Add 'BCS model' provision support

### ISSUE THREAD

**Issue by tarurar** [SubPointSolutions/spmeta2#86]
It would be nice to have an ability to deploy BCS models. 
- HOW TO: Programmatically create a SharePoint 2010 External Content Type
  http://toddbaginski.com/blog/how-to-programmatically-create-a-sharepoint-2010-external-content-type/

**Comment by SubPointSupport** [comment]
Two years later, started working on this one. @tarurar

**Comment by SubPointSupport** [comment]
Closing due to lack of popularity, moving to Nice-To-Have. Might be re-opened in one of the following sprints.
