### ISSUE TITLE
Add 'ViewURL' property in 'XsltListViewWebPartDefinition' class

### ISSUE THREAD

**Issue by ReDERO** [SubPointSolutions/spmeta2#862]
'ViewURL' property need to be added in 'XsltListViewWebPartDefinition' class. It could fix problems with View 'Tiles' for PromotedLinks, because our target site for provisioning has different language than english.

**Comment by SubPointSupport** [comment]
XsltListViewWebPartDefinition has a new property .ViewURL

Added the following tests:
* CanDeploy_XsltListViewWebPart_ByViewUrl
