### ISSUE TITLE
Add 'GroupBy' and 'DisplayColumns' properties in 'ContentByQueryWebPartDefinition' class

### ISSUE THREAD

**Issue by ReDERO** [SubPointSolutions/spmeta2#880]
There is some properties that are missed in ContentByQueryWebPartDefinition:
- GroupBy
- DisplayColumns

Here is example of properties definition:

Properties = new List<WebPartProperty>()
{
       new WebPartProperty() { Name="GroupBy", Type="string", Value="ProjectProperty.Title" },
       new WebPartProperty() { Name="DisplayColumns", Type="int", Value="4" },
}

**Comment by SubPointSupport** [comment]
Thanks! Will push in 1.2.90 release.
