### ISSUE TITLE
Multiple Questions - Taxonomy, Content Search Web part xml

### ISSUE THREAD

**Issue by ashuetawah** [SubPointSolutions/spmeta2#888]
Q1. I am looking to setup multilevel taxonomy, when I do group.addtaxonomytermset(termsetdef, set=>set.addtaxonomyterms(IEnumberable<TaxonomyTermDef>))
I do not see option to add 3 ,4 or futher upto 7 level taxonomy creation. in IEnumberable<TaxoTermDef> can you define the structure to store up to 7 level terms ?
Q2. I am setting up content search web part. I am trying by XML process. I read the file content, remove the \r\n escape sequence, but still get the issue as : Data not valid at line 1, col 1. The file content is copy of builtinwebparttemplate.contentsearchwebpart definition xml.

**Comment by SubPointSupport** [comment]
>> Q1

```cs
var model = SPMeta2Model
                  .NewSiteModel(site =>
                  {
                      site
                          .AddTaxonomyTermStore(store =>
                          {
                              store.AddTaxonomyTermGroup(group =>
                              {
                                  group.AddTaxonomyTermSet(termSet =>
                                  {
                                      termSet.AddTaxonomyTerm(term1);
                                      termSet.AddTaxonomyTerm(term2);
                                      termSet.AddTaxonomyTerm(term3, t3 =>
                                      {
                                          t3.AddTaxonomyTerm(term4);
                                          t3.AddTaxonomyTerm(term5);
                                      });
                                  });
                              });
                          });
                  });

```

As for the second question, please open up another ticket with more details on the model and the scenarios you aim to accomplish along with the errors.

Also, Yammer group might be a good idea for further questions. Cheers.
https://www.yammer.com/spmeta2feedback

**Comment by ashuetawah** [comment]
I am looking for a better way to write it either store hierarchy in List, Arrary pass the entire structure to addTaxonomyTerm, rather manually typing 100 terms in hierarhcy.
group.AddTaxonomyTermSet(termSet =>
                                  {
                                      termSet.AddTaxonomyTerm(term1, t1=> t1.addtaxonomyterm(Term11, t11 => t11.AddtaxonomyTerm(Term111);
                                  });

**Comment by SubPointSupport** [comment]
Alright, in that case you may consider working with a model tree "manually".

Use .AddDefinitionNode to add untyped definition to the model node. You would need to construct the right model tree on your own nesting term under each other.

Ultimately, SPMeta2 model is a "tree" of definitions wrapped with the ModelNode class. Every model node has a ChildModels property which is a set of the nested definitions. 

ModelNodeExtensions illustrated the tree structure, you can map out your array or whatevery you have into a SPMeta2 model tree on your own.

https://github.com/SubPointSolutions/spmeta2/blob/0ebdca59c4a9d08a5ef1f68b36fdef24e08f6c0a/SPMeta2/SPMeta2/Syntax/Default/Extensions/ModelNodeExtensions.cs
