### ISSUE TITLE
Enhance FieldLinkDefinition - DisplayName, ReadOnly, ShowInDisplayForm

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#892]
As per new SharePoint CSOM version released for SharePoint Online - August 2016 Updated
https://dev.office.com/blogs/new-sharepoint-csom-version-released-for-Office-365-august-2016-updated

**Comment by SubPointSupport** [comment]
Added implementation for DisplayName only.

**Comment by sergeisnitko** [comment]
Is it possible to implement ReadOnly option for the FieldDefinition? By default it sets to false, but we need to set it in true to enable the CountRelated in LookupFieldDefinition.
Thanks
