### ISSUE TITLE
RetractModel commented out ?

### ISSUE THREAD

**Issue by adaoust** [SubPointSolutions/spmeta2#900]
I noticed that retracting a site model with a `StandardCSOMProvisionService` doesn't do anything. After a little investigation, I noticed that the code in the `ModelServiceBase` is commented out for `RetractSite` and `RetractWeb`. Is this because the feature is not fully implemented? It would be very valuable to be able to retract a model when working with an IA that is still changing so that deployment can be tested over multiple iterations.

**Comment by SubPointSupport** [comment]
Hello @adaoust, 

Indeed, retract model is commented out and does nothing. Long story short:
* It was part of the initial design
* We haven't seen much demand on that feature, never put resources to implement it
* SPMeta2 avoids deletions as much as we can - http://docs.subpointsolutions.com/spmeta2/kb/kb-m2-000002.html

While it would be nice to have retraction support, the current pros/cons don't provide an evidence and need for the implementation. It is easier to use PowerShell to re-create web site or use other means to recreate or start from scratch if needed.

Currently, we don't have any solid plans for retract operations.

**Comment by adaoust** [comment]
Thanks for the quick reply, really appreciated!

My concern was with the Content Type Hub on O365 which cannot be deleted. I managed to use the `ModelDefinitionExtensions` and iterate through the `ContentTypeDefinition`s and the `FieldDefinition`s to delete them. I guess I was just hoping for an easier solution.

Thanks again!

Alex
