### ISSUE TITLE
Add BreakRoleInheritanceDefinition documentation

### ISSUE THREAD

**Issue by ashuetawah** [SubPointSolutions/spmeta2#901]
I have to break the list permission and either change the existing group permission from reader to contribute or add "EveryOne" with contribute permission. I could not find API to add user with a permission level to list.
I could do the permission inheritance break by 
 rootWeb.AddList(listDefinition, list => {
list.AddBreakRoleInheritance(new BreakRoleInheritanceDefinition { ClearSubscopes = false, CopyRoleAssignments= true }); });

**Comment by SubPointSupport** [comment]
Hello @ashuetawah, 

SPMeta2 supports only groups while assigning permissions. 

Just to confirm, you have a security group (SharePoint security group or Active Directory), and you would like to assign "contribute" permission for that group over a particular list. Is that correct?

**Comment by ashuetawah** [comment]
I am happy if I can add site group like site name visitor group with contribute permission. Not necessary AD group.

**Comment by ashuetawah** [comment]
In the mean time can you please let me know if I can add a AD/SP Security Group via SPMeta2 API in list after breaking the permission?

**Comment by ashuetawah** [comment]
Any help?

**Comment by SubPointSupport** [comment]
Will update docs with sample today.

**Comment by ashuetawah** [comment]
Is sample ready? could you please share the link?

**Comment by SubPointSupport** [comment]
In progress, update with samples for both BreakRoleInheritanceDefinition and ResetRoleInheritanceDefinition will be pushed in a few hours or early morning.

**Comment by SubPointSupport** [comment]
Updated scenarios page with Web Model -> SECURITY examples
http://docs.subpointsolutions.com/spmeta2/scenarios/
