### ISSUE TITLE
Consistent fallback to InternalName in both modelHost and fieldDefinitionModel

### ISSUE THREAD

**Issue by norvegec** [SubPointSolutions/spmeta2#927]
When provision 2 fields (console app, `StandardSSOMProvisionService`) I made a mistake: had provided the same `InternalName` for both fields, but different `Id`s. During deployment of this model I received 

```powershell
Processed: [18/48] - [37,5 %] - [TextFieldDefinition] 
[SPMeta2.Definitions.Fields.TextFieldDefinitionInternalName:[MyField2] Convert(p.Id):[b41ebc3e-4d1d-4235-8b89-4992db73680e] Title:[Request ID] 
FieldType:[Text] Convert(p.MaxLength):[]]

SPMeta2 Information: 3000 : Deploying model [UserFieldDefinition] RSP: [True] : [SPMeta2.Definitions.Fields.UserFieldDefinition InternalName:[MyField2] 
Convert(p.Id):[a40eed8f-2652-4f6c-99c5-f865f71a4082] 
Title: [Executor] 
# removed for brevity

SPMeta2 Information: 500 : Could not find field by ID, fallback on InternalName.
SPMeta2 Information: 4003 : Processing existing field.
SPMeta2 Information: 500 : Could not find existing field by ID, fallback on InternalName.

Unhandled Exception: SPMeta2.Exceptions.SPMeta2ModelDeploymentException: There was an error while provisioning definition. Check ModelNode prop. 
---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SPMeta2.SSOM.ModelHandlers.Fields.UserFieldModelHandler.ProcessFieldProperties(SPField field, FieldDefinition fieldModel)
```

**Comment by norvegec** [comment]
Don't have enought time to go deeper right now, but it looks like this:
Fallback aspect for host model (in my case SPField) and definition model are out of sync. My second field was found as existing SPField (by falling back to InternalName), but was not found when enumerating definition collection.

**Comment by norvegec** [comment]
Or it could be that definition collection validates/merge definition by the key and that key could be InternalName?

**Comment by norvegec** [comment]
Bottom line: it took time to found the reason of this exception, maybe some validation on `InternalName` and `Id` of definition when it is added to the collection could help?

**Comment by SubPointSupport** [comment]
Sure, could easily be done with Consider ModelNode.Validate<TDefinition>(Func<TDefinition, bool> callback) method #882 
https://github.com/SubPointSolutions/spmeta2/issues/882

We tend to avoid putting too much restrictions on the model. Would be better if people defined their own validation logic to meet the business needs. What can be suggested is to add required validation as per your needs. 

Let us know if that works for you, and the ticket can be closed. Cheers.

**Comment by norvegec** [comment]
That it. Agree, this kind of validation logic will live in our tests project for a while. I provided feedback in #882 issue (could be a bug in `Validate<>` method?). Thanks for responsive help with the issue.

**Comment by SubPointSupport** [comment]
Alright, just confirming that all good and there is no issue here to investigate.
