### ISSUE TITLE
Not possible to set SPList.DisableGridEditing property

### ISSUE THREAD

**Issue by yumitoshka** [SubPointSolutions/spmeta2#929]
There is a property in SPList called [DisableGridEditing](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.splist.disablegridediting.aspx)
But ListDefinition doesn't have it.
Is it possible to set this property using SPMeta?

SSOM 15.0.4569.1000
SPMeta2 1.2.16278.0757

**Comment by SubPointSupport** [comment]
Correct, this property is not exposed in SPMeta2 yet.

Within the model, the following snippet will do:
```cs
web.AddList(listDef, list => {

list.OnProvisioning<SPList, ListDefinition>(context =>
{
// change artifact props here
// never call .Update() for the artifact, SPMeta2 handles updates
context.Object.DisableGridEditing = true;


});
});
```

SPMeta2 has "events" before/after artifact provisioning. You need to type it correctly, and the use the following namespace:
```cs
using SPMeta2.Syntax.Default.Modern;
```

Will have a deeper look later. Most likely,  DisableGridEditing is not available in CSOM. That's why we tend to avoid putting SSOM-only props to avoid inconsistency in the model provision.

Let us know how it works for you, cheers.

**Comment by yumitoshka** [comment]
In OnProvisioning event I get null object, but OnProvisioned works perfectly.
Thanks!

**Comment by SubPointSupport** [comment]
OnProvisioning hits before a new artifact is created or existing is fetched. The first provision gives NULL as the artifact does not exist, and then the following provisions give artifact instance - artifact exists.

OnProvisioned hits after artifact was created (or fetched), the properties were mapped from definition to the artifacts but BEFORE committing changed to SharePoint. Effectively, before hitting .Update() methods for most of the artifacts. 

That gives some room to inject your own code and tune the provision process for both CSOM/SSOM APIs. A few things - your model would be API dependent having a reference to SSOM or CSOM, and such events don't get serialized while calling .ToXml() or .ToJSON() methods on the model. That prevents an easy migration of the model between CSOM/SSOM (from SP2013 to O365) plus limits the serialization process, the persistence of the model.

Nevertheless, glag it works for you, @yumitoshka. Thanks for your patience with that one!
