### ISSUE TITLE
Module file provision fails at minor version 511

### ISSUE THREAD

**Issue by thomasneuberger** [SubPointSolutions/spmeta2#930]
Hello,

if provisioning a file more than 510 times without making any other changes to it, the minor Version of the last file Version reaches 511 and can't be checked out any more. At this Point SPMeta2 provisioning crashes.

We discovered this in out test environment, where we provision our application far more often than in production. Each time when provision runs, the published Version of pages in the pages library is unpublished, so the major verison is decreased and the minor version is the last minor version of this last major version plus 1. After changing the file, checking it in and publishing it again, this newly created version mumber stays. Next time the file ist provisioned, the same happens again and the minor version incerases again. When minor version 511 is reached, trying to check the file out throws an exception not only in SPMeta2, but in the UI, too. 
A workaround is to change and publish the file outside of SPMeta2 and without unpublishing first. Since it depends of the age of the file and on how often provisioning ran since then, it is highly inpredictible when the problem occurs and on which file it will happen next. So this works only as a short-term solution if you are already stuck with a .511 version.

We still use SPMeta2 1.2.60, but looking in the source code, it seems the current release has still the same issue.

The issue occurs in SPMeta2.CSOM.ModelHandlers.ModuleFileModelHandler in method WithSafeFileOperation(List, File, Func<File, File>, Action<File>, bool).

Greetings
Thomas Neuberger

**Comment by thomasneuberger** [comment]
![proposed_solution](https://cloud.githubusercontent.com/assets/23504477/20464366/6c8d1838-af46-11e6-90ac-e44fd0f84e77.jpg)
A solution might be to check if the minor version exceeds 510 after unpublishing and if so, Publishing the file again. This way, versioning continues with a new Major version and the minor version is reset to 0. A screenshot of the code change is attached.

**Comment by SubPointSupport** [comment]
Charming!

Thanks you for reporting this issue. It was mentioned a year ago but we wouldn't be able to replicate that.
This time we clearly see the issue, will write some test and see how it goes.

Added a bug into sprint, won't push 1.2.100 until this one is replicated and fixed.

**Comment by SubPointSupport** [comment]
Aiming to fix with SPMeta2 1.2.100 release on Feb 6, 2017.

**Comment by SubPointSupport** [comment]
Implemented CSOM fix + regression test. Failed first, and then worked it out as per suggested solution by @thomasneuberger 

Will close after running SSOM related tests.

**Comment by SubPointSupport** [comment]
Same issue with SSOM. Fixing up.

**Comment by SubPointSupport** [comment]
SSOM shows that library may require approval. In that case publishing only won't help as the file still would be in the pending state. CSOM affected as well. Adding two test with .EnableModeration true/false list settings and testing the following work around on both CSOM/SSOM.

MaxMinorVersionCount is set to 50 as SharePoint seems to show some funky issue with more that 50 minor versions then it's not set by the end user. Ideally, we should compare either to 50 or to the set value by the end user (if set).

```cs
if (list != null && (list.EnableMinorVersions && file.Exists && file.Level == SPFileLevel.Published))
                {
                    file.UnPublish("Provision");

                    // Module file provision fails at minor version 511 #930
                    // https://github.com/SubPointSolutions/spmeta2/issues/930

                    // checking out .511 version will result in an exception
                    // can be cause by multiple provisions of the same file (such as on dev/test environment)
                    if (file.MinorVersion >= MaxMinorVersionCount)
                    {
                        file.Publish("Provision");

                        if (list.EnableModeration)
                            file.Approve("Provision");
                    }
                }
```
Also, SSOM tests sows significant performance degradation over 511 files to be published. Needs to be investigated as a separate issue if reported.
