### ISSUE TITLE
TaxonomyTermCustomProperty.Overwrite set to false - No properties are created.

### ISSUE THREAD

**Issue by lebiku** [SubPointSolutions/spmeta2#932]
Hi, I encountered an issue with TaxonomyTermCustomProperty.Overwrite.

### Brief description
* expected behaviour
If I set TaxonomyTermCustomProperty.Overwrite to false, I would expect term / termset properties to be created, but not to be altered afterwards.
* actual behavior
No properties are created at all if Overwrite is set to false.

### SharePoint API
SSOM, but might apply to CSOM/0365 as well.

### SPMeta2 API
1.2.70 Build, Master branch seems to have the issue, but not tested.

### SPMeta2 model
TaxonomyTermModelHandler --> {SetCustomProperty, SetLocalCustomProperty}

Discussion can be found here.
https://www.yammer.com/spmeta2feedback/#/Threads/show?threadId=809198812

**Comment by SubPointSupport** [comment]
Aiming to fix with SPMeta2 1.2.100 release on Feb 6, 2017.
