### ISSUE TITLE
The provision of calendars is not working properly

### ISSUE THREAD

**Issue by VladKosenko** [SubPointSolutions/spmeta2#935]
When we try to expand the list view in the calendar in the cloud, a blank page is displayed with the logo.
Expected to ListView calendar.

We use O365.

SPMeta2.Diagnostic.DiagnosticInfo SPMeta2FileVersion:[1.2.16278.0757]
CSOMFileVersion:[16.1.5715.1200]

My code:
public static ListViewDefinition ПодіїдепартаментуКалендар = new ListViewDefinition
		{
			Title = @"Календар",
			Url = @"EventCalendar.aspx",
			Query = @"<Where>
<DateRangesOverlap>
<FieldRef Name=""DateStarting"" /><FieldRef Name=""DateEnd"" />
<Value Type=""DateTime""><Month /></Value>
</DateRangesOverlap>
</Where>",
			Fields = new System.Collections.ObjectModel.Collection<string> {  },
			Type = BuiltInViewType.Calendar,
		};

**Comment by VladKosenko** [comment]
In studying this issue, we found a solution. In the method DeployModel of the class ListViewModelHandler when deploy calendar need to specify the ViewType.Calendar | ViewType.Recurrence for field ViewTypeKind
[Exemple calendar deploy](https://danonnet.wordpress.com/2016/03/15/how-to-create-a-calendar-view-to-show-recurrence-events-in-sharepoint-online-with-csom/)

**Comment by SubPointSupport** [comment]
In the current sprint. Will add a new property to indicate multiple Types.

**Comment by SubPointSupport** [comment]
Added .Types property. The following definition will do:
```cs
TestRandomDefinition<ListViewDefinition>(def =>
            {
                def.Hidden = false;
                def.Type = BuiltInViewType.Html;

                def.Types = new Collection<string>(new string[]{
                    BuiltInViewType.Calendar,
                    BuiltInViewType.Recurrence
                });
            });
```

As stated,  .Types property will override .Type allowing define multiple types of view such as 'ViewType.Calendar | ViewType.Recurrence'.

Added "CanDeploy_ListView_As_CalendarAndRecurrence" test, works fr both CSOM/SSOM.
