### ISSUE TITLE
UserCustomAction without Title/Description breaks Translation Export

### ISSUE THREAD

**Issue by benlime** [SubPointSolutions/spmeta2#937]
Hello,

### Brief description
Please provide short description covering two areas:
* expected behaviour
When setting a script Link the expected behavior is that I only need to provide the Following Properties to the UserCustomAction definition: `Name`, `Location`, `ScriptSrc`, `Sequence`. After provisioning, going to site settings -> Export Translations should export a valid *.resx File

* actual behavior
The UserCustomAction gets provided properly. However, if I have a MUI enabled site and I try to export translations, the export will throw a strange `SqlNullValueException`.

![image](https://cloud.githubusercontent.com/assets/981344/21587109/c75da7b0-d0d8-11e6-9f54-8a5eab1d7af2.png)

### SharePoint API
Which version of SharePoint runtime do you use? 
* CSOM

### SPMeta2 API
Which version of SPMeta2 do you use? Use the following code snippet for your convenience. It shows all the details on SPMeta2 and SharePoint runtime used.

* 1.2.90 Standard

### SPMeta2 model
Optionally, provide SPMeta2 model in which issue occurs. That helps to identify the issue and provide the solution as far as we can.
```cs
/// your SPMeta2 definitions and model here
SPMeta2Model.NewSiteModel(site =>
{
    site
       .AddUserCustomAction(new UserCustomActionDefinition
        {
            Name = "mainjs",
            Location = "ScriptLink",
            ScriptSrc = "~SiteCollection/Style Library/js/main.js",
            Sequence = 9999,
            Title = "Main Script Link", // if you omit either the title or the description, exception occurs
            Description = "Main Script Link",
        };);
});
```

**Comment by SubPointSupport** [comment]
Looks really weird. Will have a close look this week. Thanks for reporting this.
SP2013 onprem + CSOM, right?

**Comment by benlime** [comment]
Exactly, yes.

**Comment by SubPointSupport** [comment]
Aiming to fix with SPMeta2 1.2.100 release on Feb 6, 2017.

**Comment by SubPointSupport** [comment]
@benlime, which exact build of SharePoint 2016 farm do you use? Version of the farm, like here:
http://www.toddklindt.com/blog/Builds/SharePoint-2016-Builds.aspx

**Comment by SubPointSupport** [comment]
Okay, we can put required validation for both Title/Description. That would ensure that no such issue will occur later. However, that would be a breaking change as there are a lot of models out there without Title/Description.

We either can make it "optional", kinda of "warning" while provisioning models or push really hard breaking already existing provision. Preferable option is to raise a warning in logs.

Having said that, you can leverage validation API to ensure your models are in the right shape. Here is how it work:

Consider ModelNode.Validate<TDefinition>(Func<TDefinition, bool> callback) method #882
https://github.com/SubPointSolutions/spmeta2/issues/882

**Comment by SubPointSupport** [comment]
Internally, SPMeta2 should also have validation api with "warning" level. It should not throw an exception but rather sum up all warning which could potentially break provision. Warning should have explanation (KB article) on what-why, and how to avoid this.  Such API should be used for all "breaking change" validations to avoid breaking current and already existing models.

**Comment by SubPointSupport** [comment]
Add Title/Description as a required properties, indicate breaking changes via release notes and blog post.
