### ISSUE TITLE
Provision New/Edit/View Forms and WelcomePage for DocSets

### ISSUE THREAD

**Issue by ReDERO** [SubPointSolutions/spmeta2#943]
Greetings!

Could SPMeta2 provision New/Edit/View Forms and WelcomePage for DocSets?

In our case we need to add JSLink into WebParts, that generates on New/Edit/View Forms by default.

**Comment by SubPointSupport** [comment]
Unsupported yet. Would you please provide mode context and scenarios around that feature?

**Comment by SubPointSupport** [comment]
On hold unless more details and scenarios are provided.

**Comment by SubPointSupport** [comment]
Closing this one. Current work is tracked here:
DocumentSet content type settings #1045
