### ISSUE TITLE
Issue deploying fields to Site attached to Office 365 Group

### ISSUE THREAD

**Issue by Matt-Menezes** [SubPointSolutions/spmeta2#945]
More details here:
https://www.yammer.com/spmeta2feedback/#/Threads/show?threadId=839355484

Expected behaviour: Fields should be provisioned without error
Actual behaviour: First field provision works, however throws an error, preventing further provisioning

SharePoint API: O365

SPMeta2 API:
{SPMeta2.Diagnostic.DiagnosticInfo SPMeta2FileVersion:[1.2.16278.0757] SPMeta2FileLocation:[C:\xxx\bin\Debug\SPMeta2.dll] CSOMFileVersion:[16.1.5715.1200] CSOMFileLocation:[C:\xxx\bin\Debug\Microsoft.SharePoint.Client.dll] Convert(p.IsSSOMDetected):[False]}

SPMeta2 model:
Any simple field provisioning model

**Comment by SubPointSupport** [comment]
Hey @Matt-Menezes, 

So.. definetly see an issue with fields provision on site collection created for a O365 group. Lists and web definitions can be deployed but fields give us some challanges. Looking into that trying to identify the root cause, the scope and workaround. Will keep you updated here once we've got something.

**Comment by SubPointSupport** [comment]
Settign up JSLink to any value inclusing null/string.empty crashes provision on site attached to Office 365 Group. Some O365 sites might be affected as well. SP2013 never gives such issue.

Current field provision checks JSLink while setting via initial XML but does not check JSLink value later  updating it every provision. Empty strings and nulls just kills all that.
```cs
field.JSLink = definition.JSLink;
```
https://github.com/SubPointSolutions/spmeta2/blob/master/SPMeta2/SPMeta2.CSOM/ModelHandlers/FieldModelHandler.cs#L315

The following fix passes all tests. JSLinks should NOT be set in such tests, and for such sites
```cs
// setting up JS link seems to crash fields provision in some cases
            // Issue deploying fields to Site attached to Office 365 Group #945
            // https://github.com/SubPointSolutions/spmeta2/issues/945
            if (!string.IsNullOrEmpty(definition.JSLink))
                field.JSLink = definition.JSLink;
```

**Comment by SubPointSupport** [comment]
One more related conversation on Yammer:
https://www.yammer.com/spmeta2feedback/#/Threads/show?threadId=943016920
