### ISSUE TITLE
While deploying quick Launch nav with heirarchy, it deploys top level node twice

### ISSUE THREAD

**Issue by kaulshivank** [SubPointSolutions/spmeta2#947]
### Brief description
Please provide short description covering two areas:
While deploying quick Launch nav with heirarchy, it deploys top level node twice

### SharePoint API
Which version of SharePoint runtime do you use? 
O365?

/// your SPMeta2 definitions and model here
web.AddQuickLaunchNavigationNode(QuickNavigationNodes.HumanResource, node => {
node.AddQuickLaunchNavigationNode(QuickNavigationNodes.SubPage);
});

public static QuickLaunchNavigationNodeDefinition SubPage = new QuickLaunchNavigationNodeDefinition
{
Title = "Sub Page",
Url = "~site/"
};

public static QuickLaunchNavigationNodeDefinition HumanResource= new QuickLaunchNavigationNodeDefinition
{
Title = "Human Resource",
Url = "~site/"
};

Raised in yammer platform as well: 
https://www.yammer.com/spmeta2feedback/#/threads/show?threadId=840570856

**Comment by SubPointSupport** [comment]
@kaulshivank, can't replicate this issue on both CSOM/SSOM for SP2013 and for CSOM/O365. 
If there anything we may have missed?

**Comment by kaulshivank** [comment]
If you can't replicate it and no body else has raised this issue, perhaps it has something to do with my environment.
I shall try and replicate it again at my end.
