### ISSUE TITLE
UserCustomActions TitleResources Bug

### ISSUE THREAD

**Issue by AHTerrabit** [SubPointSolutions/spmeta2#950]
Hello,

i found an bug if i try to deploy a customaction like this:

        public static UserCustomActionDefinition MultiUserLogout = new UserCustomActionDefinition
        {
            Name = "tbMultiUserLogout",
            Location = "Microsoft.SharePoint.StandardMenu",
            Group = "PersonalActions",
            Sequence = 0,
            Title = Resources.Provision.CA_MultiUserLogout_Title,
            TitleResource = new List<ValueForUICulture>
            {
                new ValueForUICulture { CultureId = 1031, Value = Resources.Provision_de_DE.CA_MultiUserLogout_Title }
            },
            Description = Resources.Provision.CA_MultiUserLogout_Title,
            Url = "/_layouts/closeConnection.aspx?loginasanotheruser=true",
        };

The german translation not work. Only english title showing. No error raised.

### SharePoint API
Which version of SharePoint runtime do you use? 
CSOM

### SPMeta2 API
Which version of SPMeta2 do you use? 
I use the actual Version 1.2.100

**Comment by SubPointSupport** [comment]
Hey @AHTerrabit, thanks for reporting this.

So what's the error? Would you please share it as well as .InnerException?
Which SharePoint runtime do you use? 2013/2016/o365? The following snippet would really help:

```cs
var info = SPMeta2Diagnostic.GetDiagnosticInfo();
info.ToStirng();
```

Once done, we'll take it from there.

**Comment by AHTerrabit** [comment]
The german translation not work only english text is showing also by german localization. 
No error raised.

Here the string.

SPMeta2.Diagnostic.DiagnosticInfo SPMeta2FileVersion:[1.2.16278.0757] SPMeta2FileLocation:[C:\...\bin\Debug\SPMeta2.dll] CSOMFileVersion:[16.0.4483.1000] CSOMFileLocation:[C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.SharePoint.Client\v4.0_16.0.0.0__71e9bce111e9429c\Microsoft.SharePoint.Client.dll] Convert(p.IsSSOMDetected):[False]

**Comment by SubPointSupport** [comment]
>>C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.SharePoint.Client\v4.0_16.0.0.0__71e9bce111e9429c\Microsoft.SharePoint.Client.dll

This seems to be an old version of the CSOM runtime which does not have localization APIs. Double check if your SharePoint farm has the right CU (so that CSOM API also has localization API), and then run SPMeta2 with that CSOM assemblies (which do have localization API).

SPMeta2 automatically detects if current CSOM API has or hasn't got localization API support and acts accordingly - either uses it or skips.
