### ISSUE TITLE
Using Aggregations/AggregationsStatus in ListViewDefinition fails to deploy model (SSOM)

### ISSUE THREAD

**Issue by maxx2097** [SubPointSolutions/spmeta2#954]
Trying to set up Aggregation columns in a ListViewDefinition fails during deployment:

When using the properties

```
.Aggregations = "<FieldRef Name='TestField' Type='SUM'/>"
.AggregationsStatus = "On"
```

in a ListViewDefinition an ArgumentException is thrown during model deployment.

Exception is thrown when setting AggregationsStatus.

I tried to do this is plain SSOM and came across the same problem (but solved it).. do not access the SPView twice:

```
list.Views["TestView"].Aggregations = "<FieldRef Name='TestField' Type='SUM'/>";
list.Views["TestView"].AggregationsStatus = "On";
```

FAILS

while using...

```
var view = list.Views["TestView"];
view.Aggregations = "<FieldRef Name='TestField' Type='SUM'/>";
view.AggregationsStatus = "On";
```

SUCCEEDS

**Comment by SubPointSupport** [comment]
So do we use any ListViewDefinition with the two following props set as following?
```cs
.Aggregations = "<FieldRef Name='TestField' Type='SUM'/>"
.AggregationsStatus = "On"
```

Definetly issue, will put more testing around it ASAP.

**Comment by SubPointSupport** [comment]
Added two tests:
* CanDeploy_ListView_With_Aggregation_TitleCount
* CanDeploy_ListView_With_Aggregation_TitleSum

CSOM was broken, fixed. SSOM to be tested.

**Comment by SubPointSupport** [comment]
Fixed for both CSOM/SSOM.
