### ISSUE TITLE
Add OfficialFileHostDefinition provision support

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#957]
SPMeta2 should support "Send To" connection provision. SSOM support only for the time being.

Programmatically Create a ‘Send To’ Connection to Send Documents to The Records Center in SharePoint 2010
https://www.matdesmarais.com/2011/06/programmatically-create-a-send-to-connection-to-send-documents-to-the-records-center-in-sharepoint-2010/

**Comment by rolandoldengarm** [comment]
@SubPointSupport any ETA on this? Our current set of Powershell scripts are a bit complicated, would be good to move this part to SPMeta2.
