### ISSUE TITLE
O365 API regression - Taxonomy Group provision fails

### ISSUE THREAD

**Issue by arnieraju** [SubPointSolutions/spmeta2#959]
### Brief description
We are provisioning a Taxonomy Group using the SPMeta2.CSOM.Standard library.

Our taxonomy group model is specified as follows:

```        
internal static TaxonomyTermGroupDefinition NavigationTermGroupDefinition = new TaxonomyTermGroupDefinition
        {
            Name = "TermGroup",
            Id = new Guid("5DDAFE66-7466-4582-83B5-C2B01B68B3C8"),
            IsSiteCollectionGroup = false
        };
```
When we provision the first time, it works a treat.  When we try and re-provision using the same model, we expect it to run successfully and just update the existing group if needed.

What we get instead is the following error:

```
"Group names must be unique."
Properties:
  ServerException.ServerStackTrace = ""
  ServerException.ServerErrorCode = "-2147024809"
  ServerException.ServerErrorValue = ""
  ServerException.ServerErrorTypeName = "System.ArgumentException"
  ServerException.ServerErrorDetails = ""
  ServerException.ServerErrorTraceCorrelationId = "8f7ed69d-09c8-7093-ba57-5a05214f0188"

Stack Trace:
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at SPMeta2.CSOM.Services.Impl.DefaultClientRuntimeContextService.InternalExecuteQuery(ClientRuntimeContext context)
   at SPMeta2.CSOM.Services.Impl.DefaultClientRuntimeContextService.ExecuteQuery(ClientRuntimeContext context)
   at SPMeta2.CSOM.Extensions.ClientRuntimeContextExtensions.ExecuteQueryWithTrace(ClientRuntimeContext context)
   at SPMeta2.CSOM.Standard.ModelHandlers.Taxonomy.TaxonomyGroupModelHandler.DeployTaxonomyGroup(Object modelHost, TermStoreModelHost siteModelHost, TaxonomyTermGroupDefinition groupModel)
   at SPMeta2.CSOM.Standard.ModelHandlers.Taxonomy.TaxonomyGroupModelHandler.DeployModel(Object modelHost, DefinitionBase model)
   at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)
```

### SharePoint API
Which version of SharePoint runtime do you use? 
* CSOM

### SPMeta2 API
Which version of SPMeta2 do you use? v1.2.100

### Investigation and workaround
Looking into the DeployTaxonomyGroup method, we took a punt and decided to leave the Id out of our definition - doing this led to us being able to successfully re-run our definition again and again.

It seems that the code that looks up an existing group by Id must be broken see (https://github.com/SubPointSolutions/spmeta2/blob/a91db27843be2f800c77e1cd350be0ead7419d12/SPMeta2/SPMeta2.CSOM.Standard/ModelHandlers/Taxonomy/TaxonomyGroupModelHandler.cs#L84)

So our workaround, which gets us by is to NOT use the Id in the TaxonomyGroupDefinition.

Would be great to have this fixed though - certainly a time suck if you get caught out by this bug/feature.

**Comment by SubPointSupport** [comment]
Thanks for reporting this. Seems to be an issue, will investigate ASAP.

**Comment by arnieraju** [comment]
Thanks for the quick response!

**Comment by SubPointSupport** [comment]
Hey @arnieraju, we tested out such model and can't replicate it yet.

SP2013, the test looks as following. We create two groups with random Id/Name (yet same for the provision session), and then model gets provisioned several times + .Name property gets changed.
```cs
var termGroup1 = ModelGeneratorService.GetRandomDefinition<TaxonomyTermGroupDefinition>(def =>
            {
                def.Name = Rnd.String();
                def.Id = Rnd.Guid();

                def.IsSiteCollectionGroup = false;
            });

            var termGroup2 = termGroup1.Inherit();

            var model = SPMeta2Model
                  .NewSiteModel(site =>
                  {
                      site
                          .AddRandomTermStore(store =>
                          {
                              store.AddTaxonomyTermGroup(termGroup1);
                              store.AddTaxonomyTermGroup(termGroup2);
                          });
                  });

            TestModel(model);

```

No issues on SP2013 CSOM, SP1+.

Maybe original group in your model was created without Id? In that case actualy group in SharePoint would have a random Id assigned by SharePoint. Later if we change the model and add .Id property, then provision would try to resolve group by Id, woudn't find it and then provision would try to create a new group with the same name but different Id. That's why SharePoint might give such a weird exception.

Would you please doubl-check if:
* Your group in SharePoint has the same Id as you've got in the model
* This issue can be replicated on other VMs / SharePoint farms

Thanks in advance, we hope we can solve that for you.

**Comment by digital88** [comment]
I have same issue when provisioning termSet, i noticed provisioning behaves differently when site lcid is different.
`public static TaxonomyTermSetDefinition termSet = new TaxonomyTermSetDefinition()
{
  Name = "имя",
  LCID = 1049,
  Id = new Guid("guid_string")
}`
this fails on Russian lcid sites (lcid = 1049), but when I comment line with id, it works fine. Also provision with Id works fine on sites with lcid 1033 (English).

SP2016 on-premises, CSOM, SPMeta2 1.2.110

**Comment by SubPointSupport** [comment]
Hey @digital88, many thanks for reporting this. Now we've got more hints and may finally find the root of the issue. Really appreciate your feedback on this LCID thing.

**Comment by digital88** [comment]
Lets hope you find out the problem and fix it :)

**Comment by digital88** [comment]
Also, my termStore definition:
`public static TaxonomyTermStoreDefinition = new TaxonomyTermStoreDefinition () { UseDafaultSiteCoolectionTermStore = true }`
And term group:
`public static TaxonomyTermGroupDefinition = new TaxonomyTermGroupDefinition() {
IsSiteCollectionGroup = true // no id or name specified
}`

**Comment by arnieraju** [comment]
@SubPointSupport Thanks for the response and information above.  And apologies for the late reply.

We have updated to 1.2.110 and recently retested this and it now works for us.

Good luck tracking down the issue related to the LCID.

**Comment by SubPointSupport** [comment]
Sweet! One down, a few to go.. Hope we'll sort it out as well.

**Comment by SubPointSupport** [comment]
@arnieraju having same issues, randomly, all over the place.

Related to these issues:
* Nested terms provisioning in Office 365 fails #995
* TermSet not found #994

**Comment by SubPointSupport** [comment]
Seems to be a broader taxonomy API regression by Office365.
https://www.yammer.com/spmeta2feedback/#/Threads/show?threadId=872208619
