### ISSUE TITLE
Creating custom VS debugger visualizer for ModelNode

### ISSUE THREAD

**Issue by avishnyakov** [SubPointSolutions/spmeta2#96]
Would be nice to have advanced debugger visualization for SPMeta2 models.

**Comment by SubPointSupport** [comment]
Should be re-engineered and put back to the M2.VSExtensions project along with the VS templates.

**Comment by SubPointSupport** [comment]
Moved to https://github.com/SubPointSolutions/spmeta2-vsixextensions/issues/18
