### ISSUE TITLE
SPMeta2Model.NewFarmModel(Action<FarmModelNode> action) does not return FarmModelNode

### ISSUE THREAD

**Issue by rolandoldengarm** [SubPointSolutions/spmeta2#963]
The definition of this method says it returns a ModelNode, but it returns a FarmModelNode. 

https://github.com/SubPointSolutions/spmeta2/blob/master/SPMeta2/SPMeta2/Syntax/Default/SPMeta2Model.cs#L49

So the return type should be set to FarmModelNode.

**Comment by SubPointSupport** [comment]
Oh, old 'typo' from old refactoring. Will fix up and add some unit tests over the API contracts. 
Many thanks for reporting this one, good catch!

**Comment by SubPointSupport** [comment]
Fixed. Also added tests for SPMeta2Model.NewXXXModel() API under "Regression.SPMeta2Model.NewXXXModel" and "CI.Core" categories.
