### ISSUE TITLE
Validation Issue for Built In Security Groups

### ISSUE THREAD

**Issue by adaoust** [SubPointSolutions/spmeta2#968]
Hi @SubPointSupport,

The `SecurityGroupDefinitionValidator `ensures that the group Name isn't null, but the `BuiltInSecurityGroupDefinitions `have no Name set which makes them unusable.

My workaround was to set the name using Inherit()

`BuiltInSecurityGroupDefinitions.AssociatedMemberGroup.Inherit(def => def.Name = ((string) mySiteTitle).Replace(',', '_') + " Members");`

But I don't think this is expected behavior as the Name isn't even used for the `BuiltInSecurityGroupDefinitions`.

Thanks,

Alex

**Comment by SubPointSupport** [comment]
Right, more of a bug. 

All definitions from BuiltInSecurityGroupDefinitions set the following flags to indicate "built-in SharePoint groups":
* IsAssociatedMemberGroup 
* IsAssociatedOwnerGroup 
* IsAssociatedVisitorsGroup 

In that case provision doesn't use Name of a group to find it. And yes, validation wouldn't work assuming we've got wrong-formed definition with missed Name. 

We'll fix that up enhancing validation to handle build-in groups. very nice pick up, @adaoust

**Comment by SubPointSupport** [comment]
+ added Validation_SecurityGroup_ShouldAllow_EmptyName_If_BuiltIn and Validation_SecurityGroup_ShouldFail_On_EmptyName_If_Not_BuiltIn tests
+ add tests under CI.Core category
