### ISSUE TITLE
Enhance ListDefinition - add IsCatalog property

### ISSUE THREAD

**Issue by adaoust** [SubPointSolutions/spmeta2#985]
Hi @SubPointSupport,

I was trying to create a Catalog List using SPMeta2 and, unfortunately, the `IsCatalog` property is not part of the `ListDefinition`. I then tried to set it using the `PropertyBag` on the `ListDefinition`, but that would work either because the properties of the `PropertyBag` aren't even mapped in the CSOM `ListModelHandler`.

Thanks,

Alex

**Comment by SubPointSupport** [comment]
Alright, how would we create such a list with a C# code? We'll investigate and probably add ListDefinition.IsCatalog property, then.

As for .PropertyBag, this is a property bag for definition only. Both model node and definition has a property bag properties for that developers can store additional information associated with model node / definition.

**Comment by adaoust** [comment]
Oh! I didn't know the PropertyBag was only used for storing information about the definition. I expected it to work similarly to how the TaxonomyTermSetDefinition.CustomProperties just adds the properties to the object, but I guess it makes sense to not have that for a list?

As for provisioning a list that is a catalog, simply setting the CSOM IsCatalog property does the trick. However, I'm still investigating if it's possible to even configure any of the settings that this functionality provides through CSOM.

Thanks,

Alex

**Comment by SubPointSupport** [comment]
>I expected it to work similarly to how the TaxonomyTermSetDefinition.CustomProperties just adds the properties to the object, but I guess it makes sense to not have that for a list?

No, it does not work that way. We do one-to-one property mappings right now. However, we might add such feature with "untyped" property bags to map props to a SharePoint object. That would be a pure hell to implement and test. Right now you can you OnProvisioning/OnProvisioned events for such activities.

>>As for provisioning a list that is a catalog, simply setting the CSOM IsCatalog property does the trick. 
Yes, we'll do.

**Comment by SubPointSupport** [comment]
@adaoust, what is the exact IsCatalog property you are referring to? SPList.IsCatalog does not seem to exist. Would you please elaborate on this?

**Comment by adaoust** [comment]
Hi,

Here's the link to the official MSDN documentation for the property: [https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.list.iscatalog.aspx](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.list.iscatalog.aspx)

Unfortunately, it looks like it is read only. I am starting to think that the CSOM API does not support configuring those settings whatsoever.

Thanks for looking into this,

Alex

**Comment by SubPointSupport** [comment]
The thing is that it is not exposed over SSOM. Not too sure if we can do that. Do you have any C# examples on how to create such a list which is a catalog?

**Comment by SubPointSupport** [comment]
Closing. If there is a better way to do that programmatically - we are happy to have another look and integrate it into SPMeta2.
