### ISSUE TITLE
Error provisioning calculated field

### ISSUE THREAD

**Issue by digital88** [SubPointSolutions/spmeta2#986]
Hello.
SP2016 ENG + RUS lang pack, SPMeta2 1.2.110, CSOM
So, this model fails to be provisioned (note that TMonDatePlan is DateTimeField and already has been provisioned on site).
```cs
var fld = new CalculatedFieldDefinition()
{
	Group = Const.DefaultGroup,
	Title = "Месяц 5",
	Description = "",
	InternalName = $"Month5",
	Id = new Guid("6A7EA0EB-1B4C-4AC3-977F-03118A6848EB"),
	Formula = "=TEXT([TMonDatePlan], \"mmmm\")",
	OutputType = "Text",
	FieldReferences = new System.Collections.ObjectModel.Collection<string>()
	{
		"TMonDatePlan"
	},
};
var ct = new ContentTypeDefinition()
{
	Name = "Сотрудник 5",
	Id = new Guid("E00C66F8-4021-4305-A7D3-698E1C15A8D7"),
	Group = Const.DefaultGroup,
	ParentContentTypeId = BuiltInContentTypeId.Item
};
var site = SPMeta2Model.NewSiteModel(s =>
{
	s.AddField(fld);
	s.AddContentType(ct, c =>
	{
		c.AddContentTypeFieldLink(new ContentTypeFieldLinkDefinition()
		{
			FieldInternalName = fld.InternalName,
		});
	});
});
var list = new ListDefinition()
{
	Title = "Сотрудники 5",
	Description = "Сотрудники 5",
	TemplateType = BuiltInListTemplateTypeId.GenericList,
	CustomUrl = "Lists/Workers5",
	ContentTypesEnabled = true
};
var wweb = SPMeta2Model.NewWebModel(w =>
{
	w.AddList(list, ls =>
	{
		ls.AddContentTypeLink(new ContentTypeLinkDefinition() { ContentTypeId = ct.GetContentTypeId() });
		ls.AddListView(new ListViewDefinition()
		{
			Title = "Сотрудники 5",
			Url = "AllItems",
			IsDefault = true,
			RowLimit = 30,
			Fields = new System.Collections.ObjectModel.Collection<string>()
			{
				fld.InternalName,
			}
		});
	});
});
```

Error is:
Столбца 'Month5' не существует. Возможно, он был удален другим пользователем.
Which translates to "Field Month5 does not exists. Maybe it was deleted by another user."

Can you please help me figure out what is wrong with my models?

Edit: there is single backwards slashes before " in formula string.

**Comment by SubPointSupport** [comment]
Thanks for reporting this. Looking into it.

**Comment by SubPointSupport** [comment]
@digital88, does not that ticket help?
Problem with Calculated Site Column in Ukrainian locale (LCID: 1058) #934

**Comment by digital88** [comment]
The field itself provisioned correctly when I look in Site Colums. Formula is correct. Problem begins when i try to add list view with that field.

**Comment by SubPointSupport** [comment]
Does TMonDatePlan field (from Refs in the formula) live in the content type/list as well?

**Comment by digital88** [comment]
Just added it to test model, same error:
<code>
s.AddContentType(ct, c =>
	{
		c.AddContentTypeFieldLink(new ContentTypeFieldLinkDefinition()
		{
			FieldInternalName = fld.InternalName,
		});
                c.AddContentTypeFieldLink(new ContentTypeFieldLinkDefinition()
		{
			FieldInternalName = Fields.MonDatePlan.InternalName,
		});
	});
</code>

Field def itself:
<code>
var fld = new DateTimeFieldDefinition()
{
	Group = Const.DefaultGroup,
	Title = "Дата план",
	Description = "",
	InternalName = $"TMonDatePlan",
	Id = new Guid("guid_string_here"),
	DisplayFormat = BuiltinDateTimeFieldFormatType.DateOnly,
};
</code>

**Comment by SubPointSupport** [comment]
https://help.github.com/articles/creating-and-highlighting-code-blocks/

cs for CSharp in quotes

**Comment by digital88** [comment]
I'm puzzled. I just provisioned different calculated field on different project/site by same scenario: add field to site columns, then columns to content type, then CT to list, and finally list view to list.

Here is definition as pic (sorry, cannot copy\paste)
![image](https://cloud.githubusercontent.com/assets/10961828/24352128/00cb6ca8-12f1-11e7-91dd-9cae11888b5e.png)

**Comment by SubPointSupport** [comment]
Double check internal names of the target field everywhere: site level, content types, lists and list view. You may have had some dev/tests activities that result in such inconsistency. Maybe internal names ar different somewhere.

If it works on other site collections (or farms), then it just works as you needed and the problem somewhere in your site collection.

**Comment by SubPointSupport** [comment]
@digital88, how did you go? All works on other site collections?

**Comment by digital88** [comment]
Sorry, didn't have time yet to look into it again. I'll try before Monday, and post back asap.

**Comment by digital88** [comment]
Yep, its quotes. As soon as I changed formula to =[FieldInternalName] instead of =TEXT([FieldInternalName], "mmmm") it provisioned without errors.

**Comment by SubPointSupport** [comment]
Sweet. Closing?

**Comment by digital88** [comment]
But its a valid formula, I can set it in field settings UI on site. Problem is, quotes are provisioned incorrectly in SPMeta2 (in my case at least). Or am I  missing something? Do you have working Calculated field provision sample with formula with quotes?

**Comment by SubPointSupport** [comment]
> Problem is, quotes are provisioned incorrectly in SPMeta2 (in my case at least)

Still us? :)
[Calculated Columns - How to Use " as a text in a formula](https://social.technet.microsoft.com/Forums/sharepoint/en-US/64abc8ff-5bc5-488d-923c-5c36e93a3323/calculated-columns-how-to-use-as-a-text-in-a-formula?forum=sharepointgenerallegacy)

**Comment by digital88** [comment]
Give me 20 mins..

**Comment by digital88** [comment]
And some more observations: The above was tested in Russial LCID site, but I just provisioned successfully  full model in first post on English LCID site.

**Comment by digital88** [comment]
I think you can close this, it seems to be Sharepoint related problem. As a workaround I use powershell script to set field formula after provision.

**Comment by SubPointSupport** [comment]
Alright, closing.

**Comment by digital88** [comment]
Late update, to sort things out. Just tested some field creation using pure CSOM without SPMeta.

So apparently, in non-English LCID sites, calculated field creation with formula that references other field(s) must follow this rules:
1. To add field to site colums, formula must reference other fields by their InternalName (in English)
2. To add this site column to list, formula must reference other fields by their DisplayName (in corresponding LCID language)

Simple example (sorry for screenshot, I cant copy\paste and too lazy to retype this):
![image](https://user-images.githubusercontent.com/10961828/36367589-6ffb162a-1564-11e8-9cd6-b8e4cc81baa3.png)
