### ISSUE TITLE
Set Managed Metadata Field on PublishingPageDefinition via DefaultValues

### ISSUE THREAD

**Issue by arnieraju** [SubPointSolutions/spmeta2#987]
### Brief description
We are writing a data loader to setup demo data in a SharePoint 2016 On Premise site.  As part of the data loading we need to set a number of Managed Metadata field values.

When using the following definition in a web model, the page gets created successfully, the content type assigned, page layout configured and content and description (comments) assigned as expected.  

The demo_issuenumber (Managed Metadata Field), however, does NOT get assigned.  

```cs
        public static PublishingPageDefinition NoteFromTheChair = new PublishingPageDefinition
        {
            Title = "Demo Page Title",
            FileName = "demo-page-name.aspx",
            PageLayoutFileName = "DemoPageLayout.aspx",
            NeedOverride = true,
            ContentTypeName = "Demo Page",
            Content = @"<p>Page content</p>",
            Description = "Demo page description",
            DefaultValues = new List<FieldValue>
            {
                new FieldValue
                {
                    FieldName = "demo_issuenumber",
                    Value = "Issue 223|67b5773e-b531-4074-8a01-966cd3fe864d"
                }
            }
        };
```

After stepping through the SPMeta2 code in debug mode, we can see that the CSOMFieldLookupService.EnsureValues (Line 140) is not currently geared up to handle assignment of Managed Metadata Field values.
#### SPMeta2 Code (from debugging session)
```cs
    public virtual void EnsureValues(ListItem item, List<FieldValue> defaultValues, bool shouldOverwrite)
    {
      foreach (FieldValue defaultValue in defaultValues)
      {
        if (!string.IsNullOrEmpty(defaultValue.FieldName))
        {
          if (item.FieldValues.ContainsKey(defaultValue.FieldName))
          {
            if (!shouldOverwrite)
            {
              if (item[defaultValue.FieldName] == null)
                item[defaultValue.FieldName] = defaultValue.Value;
            }
            else
              item[defaultValue.FieldName] = defaultValue.Value;
          }
          else
            item[defaultValue.FieldName] = defaultValue.Value;
        }
        else
```

Is support for setting managed metadata fields going to be made available via the DefaultValues collection?   We are currently falling back to standard CSOM to achieve this (see code snippet at the bottom of this issue).

### SharePoint API
Which version of SharePoint runtime do you use? 
* SharePoint 2016 CSOM

### SPMeta2 API
v1.2.110

### Term Set Definition and Model
```cs
    public SiteModelNode TermStoreSiteModel ()
    {
            var termStore = new TaxonomyTermStoreDefinition
            {
                Name = "Term Store Name"
            };

            var editionNumberTermSet = new TaxonomyTermSetDefinition
            {
                Name = "Edition Numbers"
            };

            var issueTerms = GenerateEditionNumberTerms();

            var edition2017 = new TaxonomyTermDefinition 
            {
                Name = "2017"
            };

            var siteModel = SPMeta2Model.NewSiteModel();
            siteModel.AddTaxonomyTermStore(termStore, ts =>
            {
                ts.AddTaxonomyTermGroup(termGroup, group =>
                {
                    group.AddTaxonomyTermSet(editionNumberTermSet,
                        termSet =>
                        {
                            termSet.AddTaxonomyTerm(edition2017, innerTerm => innerTerm.AddTaxonomyTerms(issueTerms));

                        });
                  
                });
            });
    }
        private static List<TaxonomyTermDefinition> GenerateEditionNumberTerms()
        {
            var Issue223 = new TaxonomyTermDefinition
            {
                Name = "Issue 223",
                Id = new Guid("{67B5773E-B531-4074-8A01-966CD3FE864D}") 
            };
            var Issue224 = new TaxonomyTermDefinition
            {
                Name = "Issue 224",
                Id = new Guid("{DB4B876E-AF4F-426A-9033-19F028604C03}")
            };
            var Issue225 = new TaxonomyTermDefinition
            {
                Name = "Issue 225",
                Id = new Guid("{43E98207-9B87-483B-B630-C600004226EE}")
            };
            var Issue226 = new TaxonomyTermDefinition
            {
                Name = "Issue 226",
                Id = new Guid("{88E66DD5-1411-4D2C-9483-A475779ACB24}")
            };
            var issueTerms = new List<TaxonomyTermDefinition>();
            issueTerms.Add(Issue223);
            issueTerms.Add(Issue224);
            issueTerms.Add(Issue225);
            issueTerms.Add(Issue226);
            return issueTerms;
        }
```

### Managed Metadata via CSOM  (Snippet)
The following snippet shows how we are setting the managed metadata field  in standard CSOM.
```cs
            var issueNumber = "Issue 223|67b5773e-b531-4074-8a01-966cd3fe864d";
            Field demoField = list.Fields.GetByInternalNameOrTitle("demo_issuenumber");
            TaxonomyField demoTaxField = context.CastTo<TaxonomyField>(demoField);
            TaxonomyFieldValue demoTaxFieldValue = new TaxonomyFieldValue();
            string[] issueNumberSplit = issueNumber.Split('|');
            demoTaxFieldValue.Label = issueNumberSplit[0];
            demoTaxFieldValue.TermGuid = issueNumberSplit[1];
            demoTaxFieldValue.WssId = -1;
            demoTaxField.SetFieldValueByValue(item, demoTaxFieldValue);

            item.Update(); 
```

**Comment by SubPointSupport** [comment]
Hey @arnieraju, 

Many thank for putting all the things together. Inspecting the codebase right now. So it seem that "CSOMFieldLookupService.EnsureValues" method just sets everything as it were a string value rather than figuring out the actual type of the field and acting accordingly, right?

**Comment by SubPointSupport** [comment]
>Is support for setting managed metadata fields going to be made available via the DefaultValues collection? 
Yes, of course. We always listen the feedback implementing the most request, important stuff. Not that many things we haven't done, and setting up managed metadata values for both .DefaultValues and .Values is going to happen.

**Comment by arnieraju** [comment]
@SubPointSupport Thanks for the quick response. Correct, currently EnsureValues sets everything as if it were a string without considering the type of field.

Great to hear that it is on the cards!

**Comment by arnieraju** [comment]
@SubPointSupport after additional testing I think this issue may be a problem with my dev environment.  I have re-deployed to a fresh environment and it seems to be working.  I will do some further testing and let you know how I go.  

For now though, it probably isn't worth you spending any further time investigating this one.

Hopefully get back to you tomorrow with my findings!

**Comment by SubPointSupport** [comment]
Sweet! Let us know how it goes, we'll work it out together.

**Comment by arnieraju** [comment]
Hmmm.  Sorry about this - it seems it definitely was my mistake.  I now have this working consistently, so it was either my model or my environment.  Thanks again for the prompt response!

**Comment by SubPointSupport** [comment]
No worries, mate :)
