### ISSUE TITLE
O365 API regression - TermSet not found

### ISSUE THREAD

**Issue by rrocham** [SubPointSolutions/spmeta2#994]
Hello,

### Brief description

I found a bug when provisioning Taxonomy to the Term Store. It seems that when the Term Set is provisioned there's a little delay until the object is available to the API. The behaviour we saw was that the code would fail to provision a term for a newly created term set but re-running the model would actually create the term. The error we were getting was "_Object reference not set to an instance of an object. at SPMeta2.CSOM.Standard.ModelHandlers.Taxonomy.TaxonomyTermModelHandler.Fin
dTermInTermSet(TermSet termSet, TaxonomyTermDefinition termModel)_"

Alex D'Aoust and I fixed the problem by adding a retry operation on TaxonomyTermModelHandler.cs on the Method WithResolvingModelHost but there's probably a better way to solve it. I added the fix below just for reference.

Since this is a timing issue it might be hard to replicate but hopefully you can reproduce the problem.

### SharePoint API
O365

### SPMeta2 API
Latest Version
```
            var currentTermSet = FindTermSet(groupModelHost.HostGroup, termSetModel);
            int limit = 0;
            const int maxRetry = 10;
            while(currentTermSet == null)
            {
                if (limit > maxRetry)
                    break;

                Thread.Sleep(1000);
                currentTermSet = FindTermSet(groupModelHost.HostGroup, termSetModel);
                limit++;
            }

            action(new TermSetModelHost
            {
                HostGroup = groupModelHost.HostGroup,
                HostTermStore = groupModelHost.HostTermStore,
                HostTermSet = currentTermSet
            });
```

**Comment by SubPointSupport** [comment]
@rrocham @adaoust confirming this issue on groups and term sets, tests started falling. Apparently, it might be an issue with ALL taxonomy related things - groups, term sets and terms. We've got a fair share of tests failing as provision can't go further than just taxonomy group :)

Your suggestion with timeout works well. Fixing up and testing more. Also, similar issue was reported here:
Nested terms provisioning in Office 365 fails #995

**Comment by SubPointSupport** [comment]
This is painful.

**Comment by SubPointSupport** [comment]
Seems to be a broader taxonomy API regression by Office365.
https://www.yammer.com/spmeta2feedback/#/Threads/show?threadId=872208619
